/**
 * Build Planner Chinese (Simplified) translations
 * Machine-assisted translations - Community review needed
 * These translations were generated with AI assistance and may not be
 * accurate for gaming terminology. Native speaker contributions welcome!
 */
import type { BuildPlannerTranslations } from '../types'

export const buildplannerCn: BuildPlannerTranslations = {
  page: {
    backButton: '主页',
    buildName: '构建名称：',
    buildNamePlaceholder: '输入构建名称'
  },
  hero: {
    sectionTitle: '英雄',
    selectHero: '点击选择英雄',
    clickToSelect: '点击选择',
    selectHeroToView: '选择英雄以查看和选择特性',
    traitLevel: '等级 {level}',
    changeHero: '更换英雄',
    lvl: '等级',
    noTraitsAvailable: '无可用特性',
    selectHeroTitle: '选择英雄',
    searchHeroes: '搜索英雄...',
    noHeroesFound: '未找到英雄',
    memoryOf: '{type}之忆',
    clickToManageMemories: '点击管理记忆',
    clickToEquipMemory: '点击装备记忆',
    heroMemories: '英雄记忆',
    noMemoriesCrafted: '尚未制作任何记忆',
    craftFirstMemory: '制作你的第一个记忆',
    noTypeMemories: '没有可用的{type}记忆',
    craftMemory: '制作记忆',
    memoryNames: {
      Origin: '本源的追忆',
      Discipline: '守己的追忆',
      Progress: '奋进的追忆'
    },
    equipped: '已装备',
    equip: '装备',
    delete: '删除',
    editMemory: '编辑记忆',
    memoryTypeLabel: '记忆类型',
    baseStat: '基础属性',
    selectBaseStat: '选择基础属性...',
    fixedAffixes: '固有词缀',
    randomAffixes: '随机词缀',
    fixed: '固有',
    random: '随机',
    none: '无',
    save: '保存',
    craft: '制作',
    cancel: '取消',
    cantChangeType: '编辑时无法更改记忆类型',
    loadingMemories: '加载记忆数据中...'
  },
  talentTree: {
    sectionTitle: '天赋树',
    godTree: '神树',
    clickToSelect: '点击选择',
    classTree: '职业树',
    selectPreviousFirst: '请先选择前置天赋',
    treeNumber: '天赋树 {number}',
    selectPrevious: '选择前置',
    noTreeSelected: '未选择天赋树',
    selectGodTree: '从侧边栏选择一个神树以开始构建你的天赋树',
    selectGodTreeButton: '选择神树',
    divinity: '神格',
    slates: '石板',
    totalPoints: '总点数',
    reselectTree: '重新选择天赋树',
    reselectConfirmText: '这将重置以下天赋树及其已分配的点数：',
    confirmContinue: '确定要继续吗？',
    reselect: '重新选择',
    resetPoints: '重置点数',
    resetPointsText: '这将重置所有点数',
    totalPointsReset: '待重置总点数：',
    cancel: '取消',
    reset: '重置',
    selectSlotTitle: '选择{slot}树',
    searchTrees: '搜索天赋树...',
    loading: '加载中...',
    noTreesSearch: '未找到匹配"{query}"的天赋树',
    noTreesSlot: '此槽位无可用天赋树',
    selectNotableTitle: '选择{threshold}点显著天赋',
    notableInstruction: '你已在此天赋树中达到{threshold}点。请选择以下显著天赋之一：',
    selected: '已选择',
    noNotablesAvailable: '此天赋树在{threshold}点处无可用显著天赋。'
  },
  skills: {
    sectionTitle: '技能',
    activeSkills: '主动技能',
    passiveSkills: '被动技能',
    energy: '能量',
    maxEnergy: '最大',
    skillsTab: '技能',
    aurasTab: '光环',
    totalEnergy: '总能量：',
    overBudget: '（超出预算！）',
    resetSkills: '重置技能',
    resetSkillsConfirm: '这将重置所有主动技能和光环，包括其辅助宝石。',
    confirmContinue: '确定要继续吗？',
    selectActiveSkill: '选择主动技能',
    selectPassiveSkill: '选择被动技能',
    searchSkills: '搜索技能...',
    noSkillsFound: '未找到技能',
    selectSupport: '选择{type}（槽位 {slot}）',
    searchSupports: '搜索辅助...',
    noSupportsAvailable: '无可用辅助',
    clearSlot: '清空槽位',
    cancel: '取消',
    reset: '重置',
    removeSkill: '移除技能？',
    removeSkillConfirm: '移除此技能将同时清除分配给它的所有{count}个辅助技能。确定吗？',
    removeAll: '全部移除',
    clickToSelectActive: '点击选择主动技能',
    clickToSelectPassive: '点击选择被动技能',
    supportTypes: {
      activation: '激活媒介 / 辅助',
      magnificent: '华丽 / 辅助',
      noble: '高贵 / 辅助',
      support: '辅助',
      activationShort: '激活',
      magnificentShort: '华丽',
      nobleShort: '高贵',
      supportShort: '辅助'
    },
    stats: {
      mainStat: '主属性',
      manaCost: '魔力消耗',
      castSpeed: '施放速度',
      addedDamage: '额外伤害',
      sealedMana: '封印魔力'
    }
  },
  gear: {
    sectionTitle: '装备',
    // Inventory
    inventory: '库存 ({count})',
    addNewItem: '添加新物品',
    noItemsCrafted: '尚未制作任何物品',
    craftFirstItem: '制作您的第一件物品',
    slots: '{filled}/10 槽位',
    // Slot names
    slotsNames: {
      helmet: '头盔',
      chest: '胸甲',
      gloves: '手套',
      boots: '靴子',
      belt: '腰带',
      ring1: '戒指 1',
      ring2: '戒指 2',
      necklace: '项链',
      mainHand: '武器 1',
      offHand: '武器 2'
    },
    // Crafting modal
    craftGear: '制作装备',
    editGear: '编辑装备',
    rarity: {
      Rare: '稀有',
      Legendary: '传奇'
    },
    rarityCannotChange: '编辑时无法更改稀有度',
    // Form labels
    itemType: '物品类型',
    selectItemType: '选择物品类型...',
    baseItem: '基础物品',
    selectBaseItem: '选择基础物品...',
    itemLevel: '需求等级 {level}',
    loadingGearData: '加载装备数据中...',
    beltBlend: '腰带混合',
    towerSequence: 'TOWER 序列',
    sweetDreamAffix: '甜梦词缀',
    baseAffix: '基础词缀',
    baseAffixPriceless: '无价',
    corrosionImplicit: '腐蚀隐式',
    corrosionDisabled: '(已禁用 - 模组已腐蚀)',
    prefixes: '前缀',
    suffixes: '后缀',
    corroded: '{count}/2 已腐蚀',
    none: '无',
    // Preview
    preview: '预览',
    selectOptionsToPreview: '选择选项以预览物品',
    unnamedItem: '未命名物品',
    addToInventory: '添加到库存',
    saveChanges: '保存更改',
    // Actions
    equip: '装备',
    unequip: '卸下',
    edit: '编辑',
    delete: '删除',
    equipped: '已装备',
    clickToManage: '点击管理',
    // Category display names
    categories: {
      helmet: '防具 - 头盔',
      chest_armor: '防具 - 胸甲',
      gloves: '防具 - 手套',
      boots: '防具 - 靴子',
      shield: '盾牌',
      trinket: '饰品',
      one_handed: '单手武器',
      two_handed: '双手武器'
    },
    // Sub-type display names
    subTypes: {
      // Helmets
      str_helmet: '力量头盔',
      dex_helmet: '敏捷头盔',
      int_helmet: '智力头盔',
      // Chest
      str_chest_armor: '力量胸甲',
      dex_chest_armor: '敏捷胸甲',
      int_chest_armor: '智力胸甲',
      // Gloves
      str_gloves: '力量手套',
      dex_gloves: '敏捷手套',
      int_gloves: '智力手套',
      // Boots
      str_boots: '力量靴子',
      dex_boots: '敏捷靴子',
      int_boots: '智力靴子',
      // Shields
      str_shield: '力量盾牌',
      dex_shield: '敏捷盾牌',
      int_shield: '智力盾牌',
      // Trinkets
      belt: '腰带',
      necklace: '项链',
      ring: '戒指',
      spirit_ring: '灵戒',
      // 1H Weapons
      cane: '手杖',
      claw: '爪',
      dagger: '匕首',
      'one-handed_axe': '单手斧',
      'one-handed_hammer': '单手锤',
      'one-handed_sword': '单手剑',
      pistol: '手枪',
      rod: '法杖',
      scepter: '权杖',
      wand: '魔杖',
      // 2H Weapons
      bow: '弓',
      crossbow: '弩',
      cudgel: '棍棒',
      fire_cannon: '火炮',
      musket: '火枪',
      tin_staff: '锡杖',
      'two-handed_axe': '双手斧',
      'two-handed_hammer': '双手锤',
      'two-handed_sword': '双手剑'
    },
    // Tooltip labels
    tooltip: {
      prefixes: '前缀',
      suffixes: '后缀',
      tier: 'T'
    }
  },
  pactspirits: {
    sectionTitle: '契灵',
    level: '等级',
    selectPactspirit: '选择契灵',
    selectPlaceholder: '选择一个契灵...',
    searchPactspirits: '搜索契灵...',
    noPactspiritsFound: '未找到匹配条件的契灵。',
    microKismets: '微型命运：',
    mediumKismets: '中型命运：',
    selectKismet: '选择{type}命运',
    searchKismets: '搜索命运...',
    loadingKismets: '加载命运中...',
    noKismetsFound: '未找到命运。',
    resetUndetermined: '重置未定命运',
    resetUndeterminedText: '这将卸下未定命运并移除其扩展槽位中安装的所有命运。',
    confirmContinue: '确定要继续吗？',
    cancel: '取消',
    reset: '重置',
    close: '关闭',
    limitReached: '已达上限',
    cannotInstallKismet: '无法安装命运',
    microLimitReached: '微型命运上限（9）已达！请移除一个现有的微型命运以安装新的。',
    mediumLimitReached: '中型命运上限（4）已达！请移除一个现有的中型命运以安装新的。',
    unlockFateSlots: '解锁命运槽位',
    unlockFateDesc: '选择如何扩展此未定命运槽位：',
    fateOptionMicro: '{count}个微型命运槽位',
    fateOptionMedium: '{count}个中型命运槽位',
    fateOptionMixed: '{medium}个中型和{micro}个微型命运槽位',
    containsMultipleFates: '包含多种命运。',
    canBeExpanded: '可扩展为多个宿命槽位。',
    installMicroKismet: '安装小型宿命',
    installMediumKismet: '安装中型宿命',
    installKismet: '安装宿命',
    undeterminedFateKismet: '未定命运宿命'
  },
  buildActions: {
    saveBuild: '保存构建',
    builds: '构建列表',
    newBuild: '+ 新构建',
    noSavedBuilds: '暂无已保存的构建',
    saveExport: '保存/导出',
    exportJson: '导出为JSON',
    importJson: '从JSON导入',
    copyShareUrl: '复制分享链接',
    resetBuild: '重置构建',
    resetConfirm: '重置当前构建？所有未保存的更改将丢失。',
    saveModal: {
      title: '保存构建',
      warning: '此操作仅将构建保存到浏览器的本地存储中。如需导出，请使用导出功能。',
      cloudInfo: '此构建将保存到云端。当前限制为每个用户 {limit} 个构建。',
      cloudToggle: '激活云存储 ({count}/{limit})',
      loginPrompt: '想在云端保存您的构建吗？',
      loginLink: '登录',
      loginPromptEnd: '以使用此功能。',
      buildName: '构建名称',
      placeholder: '输入构建名称...',
      errorNoName: '请输入构建名称',
      errorSaveFailed: '保存构建失败。存储空间可能已满。',
      errorCloudLimit: '已达到云构建限制 ({limit})。删除云构建以保存更多。',
      errorCloudSaveFailed: '保存到云端失败。请重试。',
      cancel: '取消',
      save: '保存'
    },
    deleteModal: {
      title: '删除构建',
      warning: '确定要删除"{name}"吗？',
      irreversible: '此操作无法撤销。',
      cancel: '取消',
      confirm: '删除'
    }
  },
  toasts: {
    buildSaved: '构建保存成功',
    saveSuccessCloud: '构建"{name}"已保存到云端！',
    newBuildCreated: '新构建已创建',
    buildLoaded: '构建已加载',
    buildDeleted: '构建已删除',
    deleteSuccessCloud: '云端构建"{name}"已删除',
    deleteFailedCloud: '删除云端构建失败',
    loadFailed: '加载构建失败',
    buildReset: '构建已重置',
    importSuccess: '构建导入成功！',
    exportSuccess: '构建已导出',
    shareUrlCopied: '分享链接已复制到剪贴板'
  },
  importModal: {
    title: '导入构建',
    pasteJson: '粘贴JSON',
    uploadFile: '上传文件',
    dragDrop: '将.json文件拖放到此处',
    clickToSelect: '点击选择',
    selected: '已选择：',
    cancel: '取消',
    import: '导入',
    pastePlaceholder: '在此粘贴构建JSON...',
    errorNoCode: '请粘贴构建JSON',
    errorNoFile: '请先选择文件',
    errorInvalidJson: '无效的构建JSON',
    errorWrongFileType: '请选择.json文件',
    errorReadFailed: '文件读取失败'
  },
  settings: {
    title: '设置',
    language: '语言',
    done: '完成',
    comingSoon: '即将推出',
    close: '关闭设置'
  },
  divinity: {
    // Grid controls
    save: '保存',
    edit: '编辑',
    inventory: '仓库',
    reselect: '重选',
    reset: '重置',
    // Context menu
    rotateCw: '顺时针旋转',
    rotateCcw: '逆时针旋转',
    flipHorizontal: '水平翻转',
    flipVertical: '垂直翻转',
    editSlate: '编辑石板',
    removeSlate: '移除石板',
    // Inventory drawer
    inventoryTitle: '石板仓库',
    noSlatesCrafted: '尚未制作石板',
    craftFirstSlate: '制作第一块石板',
    craftSlate: '制作石板',
    // Slate card
    placed: '已放置',
    affixes: '词缀',
    affix: '词缀',
    rareSlate: '稀有石板',
    legendarySlate: '传奇石板',
    deleteSlate: '删除此石板？',
    cancel: '取消',
    delete: '删除',
    unequip: '卸下',
    // Crafting modal
    craftSlateTitle: '制作石板',
    editSlateTitle: '编辑石板',
    craftLegendarySlateTitle: '制作传奇石板',
    editLegendarySlateTitle: '编辑传奇石板',
    god: '神',
    shapeAndOrientation: '形状与方向',
    rotate: '旋转',
    flipH: '水平翻转',
    flipV: '垂直翻转',
    affixesLabel: '词缀',
    slot: '插槽',
    legendaryTemplate: '传奇模板',
    fixedAffix: '固定词缀',
    saveChanges: '保存更改',
    saveToInventory: '保存至仓库',
    cancelCrafting: '取消',
    // Node tooltip
    leftClickToAdd: '左键：添加点数',
    rightClickToRemove: '右键：移除点数',
    notableTalent: '显著天赋',
    points: '点数',
    noValidPlacement: '未找到有效放置位置。请重新排列石板以腾出空间。',
    // Affix select
    selectAffix: '选择词缀...',
    searchAffix: '输入搜索...',
    noAffixMatches: '无匹配结果',
    // God names
    godNames: {
      Hunting: '狩猎女神',
      Deception: '欺诈女神',
      Knowledge: '知识女神',
      War: '战争之神',
      Machines: '机械之神',
      Might: '力量之神',
    },
    // Node types for affix display
    nodeTypes: {
      'Micro Talent': '小型天赋',
      'Medium Talent': '中型天赋',
      'Legendary Medium Talent': '传奇中型天赋',
      'Fixed': '固定'
    }
  },
  pactspiritCategories: {
    All: '全部',
    Attack: '攻击',
    Erosion: '侵蚀',
    Spell: '法术',
    Persistent: '持续',
    Summon: '召唤',
    Survival: '生存',
    Cold: '寒冷',
    Fire: '火焰',
    Lightning: '闪电'
  },
  vorax: {
    tabName: '沃拉斯',
    editGear: '编辑沃拉斯装备',
    selectLimb: '选择部位',
    loadingData: '加载沃拉斯数据中...',
    baseAffix: '基础词缀',
    prefixes: '前缀',
    suffixes: '后缀',
    none: '无',
    selectAffix: '选择词缀...',
    toggleLegendary: '切换传奇模式',
    preview: '预览',
    unnamedItem: '未命名物品',
    voraxGear: '沃拉斯装备',
    mods: '模组',
    noModsSelected: '未选择模组',
    selectLimbToPreview: '选择部位以预览',
    addToInventory: '添加到库存',
    saveChanges: '保存更改',
    limbs: {
      chest: '胸甲',
      head: '头盔',
      hands: '手套',
      legs: '腿甲',
      neck: '项链',
      digits: '指环',
      waist: '腰带'
    }
  },
  etherealPrism: {
    // Drawer
    installPrismTitle: '安装棱镜 - 天赋树槽位 {slot}',
    installEtherealPrismTitle: '安装幽影棱镜 - 天赋树槽位 {slot}',
    installInverseImageTitle: '安装反射之影 - 天赋树槽位 {slot}',
    etherealPrisms: '异度棱镜',
    etherealPrism: '幽影棱镜',
    inverseImage: '反射之影',
    showingType: '显示类型',
    noPrismsCrafted: '尚未制作棱镜',
    craftFirstPrism: '制作第一个棱镜',
    craftPrism: '制作棱镜',
    radius: '范围',
    baseAffixLabel: '基础词缀',
    coreTalentLabel: '核心天赋',
    equipped: '已装备',
    equippedElsewhere: '已在其他位置装备',
    equip: '装备',
    edit: '编辑',
    delete: '删除',
    // Crafting Modal
    craftPrismTitle: '制作棱镜',
    craftInverseImageTitle: '制作反射之影',
    editPrismTitle: '编辑棱镜',
    etherealPrismTab: '幽影棱镜',
    inverseImageTab: '反射之影',
    baseItem: '基础物品',
    baseItemRequired: '基础物品 *',
    baseItemCannotChange: '编辑时无法更改基础物品',
    baseAffix: '基础词缀',
    baseAffixRequired: '基础词缀 *',
    coreTalent: '核心天赋',
    coreTalentRequired: '核心天赋 *',
    selectBaseItem: '选择基础棱镜',
    selectBaseAffix: '选择基础词缀',
    noCoreTalent: '无核心天赋可用',
    coreTalentFixed: '此棱镜拥有固定的核心天赋',
    randomAffixes: '随机词缀',
    modValues: '词缀数值',
    inverseImageNotAvailable: '反射之影数据不可用',
    // Slot labels
    radiusSlot: '范围槽',
    rareSlot: '稀有槽',
    legendarySlot: '传奇槽',
    radiusSlotDesc: '仅限范围模组',
    rareSlotDesc: '仅限稀有模组',
    legendarySlotDesc: '仅限传奇模组',
    selectRadiusSlot: '-- 选择范围槽 --',
    selectRareSlot: '-- 选择稀有槽 --',
    selectLegendarySlot: '-- 选择传奇槽 --',
    // Actions
    cancel: '取消',
    save: '保存',
    craft: '制作',
    // Tree Visualization
    installPrism: '安装棱镜',
    prismInstalledElsewhere: '棱镜已在其他位置安装',
    prismSlotsFull: '棱镜槽位已满',
    removePrism: '移除棱镜',
    cancelPlacement: '取消',
    // Tooltip
    additionalPointsFromPrism: '棱镜模组额外点数',
    prismAddition: '棱镜加成',
    // Inverse Image Mod Names
    microTalentEffectRange: '微型天赋效果范围',
    mediumTalentEffectRange: '中型天赋效果范围',
    legendaryMediumTalentEffectRange: '传奇中型天赋效果范围'
  }
}
