/**
 * Build Planner English translations
 * Source of truth - all other languages translate from this file
 */
import type { BuildPlannerTranslations } from '../types'

export const buildplannerEn: BuildPlannerTranslations = {
  page: {
    backButton: 'HOME',
    buildName: 'Build Name:',
    buildNamePlaceholder: 'Enter build name'
  },
  hero: {
    sectionTitle: 'HERO',
    selectHero: 'Click to select hero',
    clickToSelect: 'Click to select',
    selectHeroToView: 'Select a hero to view and choose traits',
    traitLevel: 'Level {level}',
    changeHero: 'Change Hero',
    lvl: 'Lvl',
    noTraitsAvailable: 'No traits available',
    selectHeroTitle: 'Select Hero',
    searchHeroes: 'Search heroes...',
    noHeroesFound: 'No heroes found',
    memoryOf: 'Memory of {type}',
    clickToManageMemories: 'Click to manage memories',
    clickToEquipMemory: 'Click to equip a memory',
    heroMemories: 'Hero Memories',
    noMemoriesCrafted: 'No memories crafted yet',
    craftFirstMemory: 'Craft your first Memory',
    noTypeMemories: 'No {type} memories available',
    craftMemory: 'Craft Memory',
    memoryNames: {
      Origin: 'Memory of Origin',
      Discipline: 'Memory of Discipline',
      Progress: 'Memory of Progress'
    },
    equipped: 'Equipped',
    equip: 'Equip',
    delete: 'Delete',
    editMemory: 'Edit Memory',
    memoryTypeLabel: 'Memory Type',
    baseStat: 'Base Stat',
    selectBaseStat: 'Select base stat...',
    fixedAffixes: 'Fixed Affixes',
    randomAffixes: 'Random Affixes',
    fixed: 'Fixed',
    random: 'Random',
    none: 'None',
    save: 'Save',
    craft: 'Craft',
    cancel: 'Cancel',
    cantChangeType: 'Memory type cannot be changed when editing',
    loadingMemories: 'Loading memory data...'
  },
  talentTree: {
    sectionTitle: 'TALENT TREE',
    godTree: 'God Tree',
    clickToSelect: 'Click to select',
    classTree: 'Class Tree',
    selectPreviousFirst: 'Select previous first',
    treeNumber: 'Tree {number}',
    selectPrevious: 'Select previous',
    noTreeSelected: 'No Tree Selected',
    selectGodTree: 'Select a God Tree from the sidebar to begin building your talent tree',
    selectGodTreeButton: 'Select God Tree',
    divinity: 'Divinity',
    slates: 'Slates',
    totalPoints: 'Total Points',
    reselectTree: 'Reselect Tree',
    reselectConfirmText: 'This will reset the following trees and their allocated points:',
    confirmContinue: 'Are you sure you want to continue?',
    reselect: 'Reselect',
    resetPoints: 'Reset Points',
    resetPointsText: 'This will reset all points in',
    totalPointsReset: 'Total points to be reset:',
    cancel: 'Cancel',
    reset: 'Reset',
    selectSlotTitle: 'Select {slot} Tree',
    searchTrees: 'Search trees...',
    loading: 'Loading...',
    noTreesSearch: 'No trees found matching "{query}"',
    noTreesSlot: 'No trees available for this slot',
    selectNotableTitle: 'Select {threshold}-Point Notable',
    notableInstruction: 'You\'ve reached {threshold} points in this tree. Select one of the following notables:',
    selected: 'Selected',
    noNotablesAvailable: 'No notables available at {threshold} points for this tree.'
  },
  skills: {
    sectionTitle: 'SKILLS',
    activeSkills: 'Active Skills',
    passiveSkills: 'Passive Skills',
    energy: 'Energy',
    maxEnergy: 'max',
    skillsTab: 'Skills',
    aurasTab: 'Auras',
    totalEnergy: 'Total Energy:',
    overBudget: '(Over budget!)',
    resetSkills: 'Reset Skills',
    resetSkillsConfirm: 'This will reset all active skills and auras, including their support gems.',
    confirmContinue: 'Are you sure you want to continue?',
    selectActiveSkill: 'Select Active Skill',
    selectPassiveSkill: 'Select Passive Skill',
    searchSkills: 'Search skills...',
    noSkillsFound: 'No skills found',
    selectSupport: 'Select {type} (Slot {slot})',
    searchSupports: 'Search supports...',
    noSupportsAvailable: 'No supports available',
    clearSlot: 'Clear Slot',
    cancel: 'Cancel',
    reset: 'Reset',
    removeSkill: 'Remove Skill?',
    removeSkillConfirm: 'Removing this skill will also clear all {count} support skill(s) allocated to it. Are you sure?',
    removeAll: 'Remove All',
    clickToSelectActive: 'Click to select an active skill',
    clickToSelectPassive: 'Click to select a passive skill',
    supportTypes: {
      activation: 'Activation Medium / Support',
      magnificent: 'Magnificent / Support',
      noble: 'Noble / Support',
      support: 'Support',
      activationShort: 'Activation',
      magnificentShort: 'Magnificent',
      nobleShort: 'Noble',
      supportShort: 'Support'
    },
    stats: {
      mainStat: 'Main Stat',
      manaCost: 'Mana Cost',
      castSpeed: 'Cast Speed',
      addedDamage: 'Added Damage',
      sealedMana: 'Sealed Mana'
    }
  },
  gear: {
    sectionTitle: 'GEAR',
    // Inventory
    inventory: 'Inventory ({count})',
    addNewItem: 'Add New Item',
    noItemsCrafted: 'No items crafted yet',
    craftFirstItem: 'Craft your first item',
    slots: '{filled}/10 slots',
    // Slot names
    slotsNames: {
      helmet: 'Helmet',
      chest: 'Chest Armor',
      gloves: 'Gloves',
      boots: 'Boots',
      belt: 'Belt',
      ring1: 'Ring 1',
      ring2: 'Ring 2',
      necklace: 'Necklace',
      mainHand: 'Weapon 1',
      offHand: 'Weapon 2'
    },
    // Crafting modal
    craftGear: 'Craft Gear',
    editGear: 'Edit Gear',
    rarity: {
      Rare: 'Rare',
      Legendary: 'Legendary'
    },
    rarityCannotChange: 'Rarity cannot be changed when editing',
    // Form labels
    itemType: 'Item Type',
    selectItemType: 'Select item type...',
    baseItem: 'Base Item',
    selectBaseItem: 'Select base item...',
    itemLevel: 'Lv. {level}',
    loadingGearData: 'Loading gear data...',
    beltBlend: 'Belt Blend',
    towerSequence: 'TOWER Sequence',
    sweetDreamAffix: 'Sweet Dream Affix',
    baseAffix: 'Base Affix',
    baseAffixPriceless: '(Priceless)',
    corrosionImplicit: 'Corrosion Implicit',
    corrosionDisabled: '(disabled - mods are corroded)',
    prefixes: 'Prefixes',
    suffixes: 'Suffixes',
    corroded: '{count}/2 corroded',
    none: 'None',
    // Preview
    preview: 'Preview',
    selectOptionsToPreview: 'Select options to preview item',
    unnamedItem: 'Unnamed Item',
    addToInventory: 'Add to Inventory',
    saveChanges: 'Save Changes',
    // Actions
    equip: 'Equip',
    unequip: 'Unequip',
    edit: 'Edit',
    delete: 'Delete',
    equipped: 'E',
    clickToManage: 'Click to manage',
    // Category display names
    categories: {
      helmet: 'Armor - Helmet',
      chest_armor: 'Armor - Chest',
      gloves: 'Armor - Gloves',
      boots: 'Armor - Boots',
      shield: 'Shield',
      trinket: 'Trinket',
      one_handed: '1H Weapon',
      two_handed: '2H Weapon'
    },
    // Sub-type display names
    subTypes: {
      // Helmets
      str_helmet: 'STR Helmet',
      dex_helmet: 'DEX Helmet',
      int_helmet: 'INT Helmet',
      // Chest
      str_chest_armor: 'STR Chest Armor',
      dex_chest_armor: 'DEX Chest Armor',
      int_chest_armor: 'INT Chest Armor',
      // Gloves
      str_gloves: 'STR Gloves',
      dex_gloves: 'DEX Gloves',
      int_gloves: 'INT Gloves',
      // Boots
      str_boots: 'STR Boots',
      dex_boots: 'DEX Boots',
      int_boots: 'INT Boots',
      // Shields
      str_shield: 'STR Shield',
      dex_shield: 'DEX Shield',
      int_shield: 'INT Shield',
      // Trinkets
      belt: 'Belt',
      necklace: 'Necklace',
      ring: 'Ring',
      spirit_ring: 'Spirit Ring',
      // 1H Weapons
      cane: 'Cane',
      claw: 'Claw',
      dagger: 'Dagger',
      'one-handed_axe': 'One-Handed Axe',
      'one-handed_hammer': 'One-Handed Hammer',
      'one-handed_sword': 'One-Handed Sword',
      pistol: 'Pistol',
      rod: 'Rod',
      scepter: 'Scepter',
      wand: 'Wand',
      // 2H Weapons
      bow: 'Bow',
      crossbow: 'Crossbow',
      cudgel: 'Cudgel',
      fire_cannon: 'Fire Cannon',
      musket: 'Musket',
      tin_staff: 'Tin Staff',
      'two-handed_axe': 'Two-Handed Axe',
      'two-handed_hammer': 'Two-Handed Hammer',
      'two-handed_sword': 'Two-Handed Sword'
    },
    // Tooltip labels
    tooltip: {
      prefixes: 'Prefixes',
      suffixes: 'Suffixes',
      tier: 'T'
    }
  },
  pactspirits: {
    sectionTitle: 'PACTSPIRITS',
    level: 'Level',
    selectPactspirit: 'Select Pactspirit',
    selectPlaceholder: 'Select a pactspirit...',
    searchPactspirits: 'Search pactspirits...',
    noPactspiritsFound: 'No pactspirits found matching your criteria.',
    microKismets: 'Micro Kismets:',
    mediumKismets: 'Medium Kismets:',
    selectKismet: 'Select {type} Kismet',
    searchKismets: 'Search kismets...',
    loadingKismets: 'Loading kismets...',
    noKismetsFound: 'No kismets found.',
    resetUndetermined: 'Reset Undetermined Fate',
    resetUndeterminedText: 'This will unequip the Undetermined Fate and remove all Kismets installed in its expanded slots.',
    confirmContinue: 'Are you sure you want to continue?',
    cancel: 'Cancel',
    reset: 'Reset',
    close: 'Close',
    limitReached: 'Limit Reached',
    cannotInstallKismet: 'Cannot Install Kismet',
    microLimitReached: 'Micro Kismet limit (9) reached! Please remove an existing Micro Fate to install a new one.',
    mediumLimitReached: 'Medium Kismet limit (4) reached! Please remove an existing Medium Fate to install a new one.',
    unlockFateSlots: 'Unlock Fate Slots',
    unlockFateDesc: 'Select how to expand this Undetermined Fate slot:',
    fateOptionMicro: '{count} Micro Fate Slot',
    fateOptionMedium: '{count} Medium Fate Slot',
    fateOptionMixed: '{medium} Medium & {micro} Micro Fate Slot',
    containsMultipleFates: 'Contains multiple fates.',
    canBeExpanded: 'Can be expanded into multiple Kismet slots.',
    installMicroKismet: 'Install a Micro Kismet',
    installMediumKismet: 'Install a Medium Kismet',
    installKismet: 'Install a Kismet',
    undeterminedFateKismet: 'Undetermined Fate Kismet'
  },
  buildActions: {
    saveBuild: 'Save Build',
    builds: 'Builds',
    newBuild: '+ New Build',
    noSavedBuilds: 'No saved builds',
    saveExport: 'Save/Export',
    exportJson: 'Export as JSON',
    importJson: 'Import from JSON',
    copyShareUrl: 'Copy Share URL',
    resetBuild: 'Reset Build',
    resetConfirm: 'Reset current build? All unsaved changes will be lost.',
    saveModal: {
      title: 'Save Build',
      warning: 'This saves only into your browser\'s local storage. Use Export to create a portable file.',
      cloudInfo: 'This build will be saved to the cloud. Current limit is {limit} builds per user.',
      cloudToggle: 'Activate Cloud Save ({count}/{limit})',
      loginPrompt: 'Want to save your builds in the Cloud?',
      loginLink: 'Login',
      loginPromptEnd: 'to use this feature.',
      buildName: 'Build Name',
      placeholder: 'Enter build name...',
      errorNoName: 'Please enter a build name',
      errorSaveFailed: 'Failed to save build. Storage may be full.',
      errorCloudLimit: 'Cloud build limit reached ({limit}). Delete a cloud build to save more.',
      errorCloudSaveFailed: 'Failed to save to cloud. Please try again.',
      cancel: 'Cancel',
      save: 'Save'
    },
    deleteModal: {
      title: 'Delete Build',
      warning: 'Are you sure you want to delete "{name}"?',
      irreversible: 'This action cannot be undone.',
      cancel: 'Cancel',
      confirm: 'Delete'
    }
  },
  toasts: {
    buildSaved: 'Build saved successfully',
    saveSuccessCloud: 'Build "{name}" saved to cloud!',
    newBuildCreated: 'New build created',
    buildLoaded: 'Build loaded',
    buildDeleted: 'Build deleted',
    deleteSuccessCloud: 'Cloud build "{name}" deleted',
    deleteFailedCloud: 'Failed to delete cloud build',
    loadFailed: 'Failed to load build',
    buildReset: 'Build reset',
    importSuccess: 'Build imported successfully!',
    exportSuccess: 'Build exported',
    shareUrlCopied: 'Share URL copied to clipboard'
  },
  importModal: {
    title: 'Import Build',
    pasteJson: 'Paste JSON',
    uploadFile: 'Upload File',
    dragDrop: 'Drag & drop a .json file here',
    clickToSelect: 'click to select',
    selected: 'Selected:',
    cancel: 'Cancel',
    import: 'Import',
    pastePlaceholder: 'Paste your build JSON here...',
    errorNoCode: 'Please paste a build JSON',
    errorNoFile: 'Please select a file first',
    errorInvalidJson: 'Invalid build JSON',
    errorWrongFileType: 'Please select a .json file',
    errorReadFailed: 'Failed to read file'
  },
  settings: {
    title: 'Settings',
    language: 'Language',
    done: 'Done',
    comingSoon: 'Coming Soon',
    close: 'Close settings'
  },
  divinity: {
    // Grid controls
    save: 'Save',
    edit: 'Edit',
    inventory: 'Inventory',
    reselect: 'Reselect',
    reset: 'Reset',
    // Context menu
    rotateCw: 'Rotate clockwise',
    rotateCcw: 'Rotate counter-clockwise',
    flipHorizontal: 'Flip horizontal',
    flipVertical: 'Flip vertical',
    editSlate: 'Edit slate',
    removeSlate: 'Remove slate',
    // Inventory drawer
    inventoryTitle: 'Slate Inventory',
    noSlatesCrafted: 'No slates crafted yet',
    craftFirstSlate: 'Craft your first Slate',
    craftSlate: 'Craft Slate',
    // Slate card
    placed: 'Placed',
    affixes: 'affixes',
    affix: 'affix',
    rareSlate: 'Rare Slate',
    legendarySlate: 'Legendary Slate',
    deleteSlate: 'Delete this slate?',
    cancel: 'Cancel',
    delete: 'Delete',
    unequip: 'Unequip',
    // Crafting modal
    craftSlateTitle: 'Craft Slate',
    editSlateTitle: 'Edit Slate',
    craftLegendarySlateTitle: 'Craft Legendary Slate',
    editLegendarySlateTitle: 'Edit Legendary Slate',
    god: 'God',
    shapeAndOrientation: 'Shape & Orientation',
    rotate: 'Rotate',
    flipH: 'Flip H',
    flipV: 'Flip V',
    affixesLabel: 'Affixes',
    slot: 'Slot',
    legendaryTemplate: 'Legendary Template',
    fixedAffix: 'Fixed Affix',
    saveChanges: 'Save Changes',
    saveToInventory: 'Save to Inventory',
    cancelCrafting: 'Cancel',
    // Node tooltip
    leftClickToAdd: 'Left-click: Add point',
    rightClickToRemove: 'Right-click: Remove point',
    notableTalent: 'Notable Talent',
    points: 'points',
    // Toast messages
    noValidPlacement: 'No valid placement found. Rearrange your slates to make room.',
    // Affix select
    selectAffix: 'Select affix...',
    searchAffix: 'Type to search...',
    noAffixMatches: 'No matches',
    // God names
    godNames: {
      Hunting: 'Goddess of Hunting',
      Deception: 'Goddess of Deception',
      Knowledge: 'Goddess of Knowledge',
      War: 'God of War',
      Machines: 'God of Machines',
      Might: 'God of Might',
    },
    // Node types for affix display
    nodeTypes: {
      'Micro Talent': 'Micro Talent',
      'Medium Talent': 'Medium Talent',
      'Legendary Medium Talent': 'Legendary Medium Talent',
      'Fixed': 'Fixed'
    }
  },
  pactspiritCategories: {
    All: 'All',
    Attack: 'Attack',
    Erosion: 'Erosion',
    Spell: 'Spell',
    Persistent: 'Persistent',
    Summon: 'Summon',
    Survival: 'Survival',
    Cold: 'Cold',
    Fire: 'Fire',
    Lightning: 'Lightning'
  },
  vorax: {
    tabName: 'Vorax',
    editGear: 'Edit Vorax Gear',
    selectLimb: 'Select Limb',
    loadingData: 'Loading Vorax data...',
    baseAffix: 'Base Affix',
    prefixes: 'Prefixes',
    suffixes: 'Suffixes',
    none: 'None',
    selectAffix: 'Select affix...',
    toggleLegendary: 'Toggle Legendary Mode',
    preview: 'Preview',
    unnamedItem: 'Unnamed Item',
    voraxGear: 'Vorax Gear',
    mods: 'Mods',
    noModsSelected: 'No mods selected',
    selectLimbToPreview: 'Select a limb to preview',
    addToInventory: 'Add to Inventory',
    saveChanges: 'Save Changes',
    limbs: {
      chest: 'Chest',
      head: 'Head',
      hands: 'Hands',
      legs: 'Legs',
      neck: 'Neck',
      digits: 'Digits',
      waist: 'Waist'
    }
  },
  etherealPrism: {
    // Drawer
    installPrismTitle: 'Install Prism - Tree Slot {slot}',
    installEtherealPrismTitle: 'Install Ethereal Prism - Tree Slot {slot}',
    installInverseImageTitle: 'Install Inverse Image - Tree Slot {slot}',
    etherealPrisms: 'Ethereal Prisms',
    etherealPrism: 'Ethereal Prism',
    inverseImage: 'Inverse Image',
    showingType: 'Showing',
    noPrismsCrafted: 'No prisms crafted yet',
    craftFirstPrism: 'Craft First Prism',
    craftPrism: 'Craft Prism',
    radius: 'Radius',
    baseAffixLabel: 'Base Affix',
    coreTalentLabel: 'Core Talent',
    equipped: 'Equipped',
    equippedElsewhere: 'Equipped Elsewhere',
    equip: 'Equip',
    edit: 'Edit',
    delete: 'Delete',
    // Crafting Modal
    craftPrismTitle: 'Craft Prism',
    craftInverseImageTitle: 'Craft Inverse Image',
    editPrismTitle: 'Edit Prism',
    etherealPrismTab: 'Ethereal Prism',
    inverseImageTab: 'Inverse Image',
    baseItem: 'Base Item',
    baseItemRequired: 'Base Item *',
    baseItemCannotChange: 'Base item cannot be changed when editing',
    selectBaseItem: 'Select Base Prism',
    baseAffix: 'Base Affix',
    baseAffixRequired: 'Base Affix *',
    selectBaseAffix: 'Select Base Affix',
    coreTalent: 'Core Talent',
    coreTalentRequired: 'Core Talent *',
    noCoreTalent: 'No core talent available',
    coreTalentFixed: 'This prism has a fixed core talent',
    randomAffixes: 'Random Affixes',
    modValues: 'Mod Values',
    inverseImageNotAvailable: 'Inverse Image data not available',
    // Slot labels
    radiusSlot: 'Radius Slot',
    rareSlot: 'Rare Slot',
    legendarySlot: 'Legendary Slot',
    radiusSlotDesc: 'Only Radius mods',
    rareSlotDesc: 'Only Rare mods',
    legendarySlotDesc: 'Only Legendary mods',
    selectRadiusSlot: '-- Select Radius Slot --',
    selectRareSlot: '-- Select Rare Slot --',
    selectLegendarySlot: '-- Select Legendary Slot --',
    // Actions
    cancel: 'Cancel',
    save: 'Save',
    craft: 'Craft',
    // Tree Visualization
    installPrism: 'Install Prism',
    prismInstalledElsewhere: 'Prism Installed Elsewhere',
    prismSlotsFull: 'All Prism Slots Full',
    removePrism: 'Remove Prism',
    cancelPlacement: 'Cancel',
    // Tooltip
    additionalPointsFromPrism: 'Additional points from Prism Mod',
    prismAddition: 'Prism Addition',
    // Inverse Image Mod Names
    microTalentEffectRange: 'Micro Talent Effect Range',
    mediumTalentEffectRange: 'Medium Talent Effect Range',
    legendaryMediumTalentEffectRange: 'Legendary Medium Talent Effect Range'
  }
}
