/**
 * Build Planner Japanese translations
 * Machine-assisted translations - Community review needed
 * These translations were generated with AI assistance and may not be
 * accurate for gaming terminology. Native speaker contributions welcome!
 */
import type { BuildPlannerTranslations } from '../types'

export const buildplannerJa: BuildPlannerTranslations = {
  page: {
    backButton: 'ホーム',
    buildName: 'ビルド名：',
    buildNamePlaceholder: 'ビルド名を入力'
  },
  hero: {
    sectionTitle: 'ヒーロー',
    selectHero: 'ヒーローを選択',
    clickToSelect: 'クリックして選択',
    selectHeroToView: '特性を表示して選択するにはヒーローを選択してください',
    traitLevel: 'レベル {level}',
    changeHero: 'ヒーロー変更',
    lvl: 'Lv',
    noTraitsAvailable: '利用可能な特性がありません',
    selectHeroTitle: 'ヒーロー選択',
    searchHeroes: 'ヒーローを検索...',
    noHeroesFound: 'ヒーローが見つかりません',
    memoryOf: '{type}の記憶',
    clickToManageMemories: 'クリックして記憶を管理',
    clickToEquipMemory: 'クリックして記憶を装備',
    heroMemories: 'ヒーローメモリー',
    noMemoriesCrafted: 'まだ記憶が作成されていません',
    craftFirstMemory: '最初の記憶を作成する',
    noTypeMemories: '{type}の記憶がありません',
    craftMemory: '記憶を作成',
    memoryNames: {
      Origin: '本源の追憶',
      Discipline: '守りの追憶',
      Progress: '攻めの追憶'
    },
    equipped: '装備中',
    equip: '装備',
    delete: '削除',
    editMemory: '追憶を編集',
    memoryTypeLabel: '追憶タイプ',
    baseStat: '基礎ステータス',
    selectBaseStat: '基礎ステータスを選択...',
    fixedAffixes: '固有修飾詞',
    randomAffixes: 'ランダム修飾詞',
    fixed: '固有',
    random: 'ランダム',
    none: 'なし',
    save: '保存',
    craft: '作成',
    cancel: 'キャンセル',
    cantChangeType: '編集時に追憶タイプは変更できません',
    loadingMemories: '追憶データを読み込み中...'
  },
  talentTree: {
    sectionTitle: 'タレントツリー',
    godTree: 'ゴッドツリー',
    clickToSelect: 'クリックして選択',
    classTree: 'クラスツリー',
    selectPreviousFirst: 'まず前のツリーを選択してください',
    treeNumber: 'ツリー {number}',
    selectPrevious: '前を選択',
    noTreeSelected: 'ツリーが選択されていません',
    selectGodTree: 'タレントツリーの構築を開始するには、サイドバーからゴッドツリーを選択してください',
    selectGodTreeButton: 'ゴッドツリーを選択',
    divinity: '神格',
    slates: 'スレート',
    totalPoints: '合計ポイント',
    reselectTree: 'ツリーを再選択',
    reselectConfirmText: '以下のツリーと割り当てられたポイントがリセットされます：',
    confirmContinue: '続行しますか？',
    reselect: '再選択',
    resetPoints: 'ポイントリセット',
    resetPointsText: 'すべてのポイントをリセットします',
    totalPointsReset: 'リセットされるポイント数：',
    cancel: 'キャンセル',
    reset: 'リセット',
    selectSlotTitle: '{slot}ツリーを選択',
    searchTrees: 'ツリーを検索...',
    loading: '読み込み中...',
    noTreesSearch: '「{query}」に一致するツリーが見つかりません',
    noTreesSlot: 'このスロットに利用可能なツリーがありません',
    selectNotableTitle: '{threshold}ポイント顕著天賦を選択',
    notableInstruction: 'このツリーで{threshold}ポイントに達しました。以下の顕著天賦から1つ選択してください：',
    selected: '選択済み',
    noNotablesAvailable: 'このツリーの{threshold}ポイントで利用可能な顕著天賦がありません。'
  },
  skills: {
    sectionTitle: 'スキル',
    activeSkills: 'アクティブスキル',
    passiveSkills: 'パッシブスキル',
    energy: 'エネルギー',
    maxEnergy: '最大',
    skillsTab: 'スキル',
    aurasTab: 'オーラ',
    totalEnergy: '合計エネルギー：',
    overBudget: '（予算超過！）',
    resetSkills: 'スキルリセット',
    resetSkillsConfirm: 'すべてのアクティブスキルとオーラ、サポートジェムを含めてリセットします。',
    confirmContinue: '続行しますか？',
    selectActiveSkill: 'アクティブスキルを選択',
    selectPassiveSkill: 'パッシブスキルを選択',
    searchSkills: 'スキルを検索...',
    noSkillsFound: 'スキルが見つかりません',
    selectSupport: '{type}を選択（スロット {slot}）',
    searchSupports: 'サポートを検索...',
    noSupportsAvailable: '利用可能なサポートがありません',
    clearSlot: 'スロットをクリア',
    cancel: 'キャンセル',
    reset: 'リセット',
    removeSkill: 'スキルを削除しますか？',
    removeSkillConfirm: 'このスキルを削除すると、割り当てられた{count}個のサポートスキルもすべてクリアされます。よろしいですか？',
    removeAll: 'すべて削除',
    clickToSelectActive: 'クリックしてアクティブスキルを選択',
    clickToSelectPassive: 'クリックしてパッシブスキルを選択',
    supportTypes: {
      activation: '活性媒体 / サポート',
      magnificent: '壮大 / サポート',
      noble: '高貴 / サポート',
      support: 'サポート',
      activationShort: '活性',
      magnificentShort: '壮大',
      nobleShort: '高貴',
      supportShort: 'サポート'
    },
    stats: {
      mainStat: '主能力値',
      manaCost: 'マナコスト',
      castSpeed: '詠唱速度',
      addedDamage: '追加ダメージ',
      sealedMana: '封印マナ'
    }
  },
  gear: {
    sectionTitle: '装備',
    // Inventory
    inventory: 'インベントリ ({count})',
    addNewItem: '新規アイテム追加',
    noItemsCrafted: '作成されたアイテムはありません',
    craftFirstItem: '最初のアイテムを作成',
    slots: '{filled}/10 スロット',
    // Slot names
    slotsNames: {
      helmet: 'ヘルメット',
      chest: '胸鎧',
      gloves: '手袋',
      boots: 'ブーツ',
      belt: 'ベルト',
      ring1: '指輪 1',
      ring2: '指輪 2',
      necklace: 'ネックレス',
      mainHand: '武器 1',
      offHand: '武器 2'
    },
    // Crafting modal
    craftGear: '装備を作成',
    editGear: '装備を編集',
    rarity: {
      Rare: 'レア',
      Legendary: 'レジェンダリー'
    },
    rarityCannotChange: '編集中はレアリティを変更できません',
    // Form labels
    itemType: 'アイテムタイプ',
    selectItemType: 'アイテムタイプを選択...',
    baseItem: 'ベースアイテム',
    selectBaseItem: 'ベースアイテムを選択...',
    itemLevel: '要求レベル {level}',
    loadingGearData: '装備データを読み込み中...',
    beltBlend: 'ベルトブレンド',
    towerSequence: 'TOWERシークエンス',
    sweetDreamAffix: 'スイートドリームアフィックス',
    baseAffix: 'ベースアフィックス',
    baseAffixPriceless: 'プライスレス',
    corrosionImplicit: '腐食インプリシット',
    corrosionDisabled: '(無効 - モッドが腐食しています)',
    prefixes: 'プレフィックス',
    suffixes: 'サフィックス',
    corroded: '{count}/2 腐食',
    none: 'なし',
    // Preview
    preview: 'プレビュー',
    selectOptionsToPreview: 'プレビューするオプションを選択',
    unnamedItem: '名前なしアイテム',
    addToInventory: 'インベントリに追加',
    saveChanges: '変更を保存',
    // Actions
    equip: '装備',
    unequip: '装備解除',
    edit: '編集',
    delete: '削除',
    equipped: '装備中',
    clickToManage: 'クリックして管理',
    // Category display names
    categories: {
      helmet: '防具 - ヘルメット',
      chest_armor: '防具 - 胸鎧',
      gloves: '防具 - 手袋',
      boots: '防具 - ブーツ',
      shield: '盾',
      trinket: '装飾品',
      one_handed: '片手武器',
      two_handed: '両手武器'
    },
    // Sub-type display names
    subTypes: {
      // Helmets
      str_helmet: 'STRヘルメット',
      dex_helmet: 'DEXヘルメット',
      int_helmet: 'INTヘルメット',
      // Chest
      str_chest_armor: 'STR胸鎧',
      dex_chest_armor: 'DEX胸鎧',
      int_chest_armor: 'INT胸鎧',
      // Gloves
      str_gloves: 'STR手袋',
      dex_gloves: 'DEX手袋',
      int_gloves: 'INT手袋',
      // Boots
      str_boots: 'STRブーツ',
      dex_boots: 'DEXブーツ',
      int_boots: 'INTブーツ',
      // Shields
      str_shield: 'STR盾',
      dex_shield: 'DEX盾',
      int_shield: 'INT盾',
      // Trinkets
      belt: 'ベルト',
      necklace: 'ネックレス',
      ring: '指輪',
      spirit_ring: 'スピリットリング',
      // 1H Weapons
      cane: '杖',
      claw: '爪',
      dagger: '短剣',
      'one-handed_axe': '片手斧',
      'one-handed_hammer': '片手ハンマー',
      'one-handed_sword': '片手剣',
      pistol: 'ピストル',
      rod: 'ロッド',
      scepter: 'セプター',
      wand: 'ワンド',
      // 2H Weapons
      bow: '弓',
      crossbow: 'クロスボウ',
      cudgel: '棍棒',
      fire_cannon: '火炎砲',
      musket: 'マスケット銃',
      tin_staff: '錫杖',
      'two-handed_axe': '両手斧',
      'two-handed_hammer': '両手ハンマー',
      'two-handed_sword': '両手剣'
    },
    // Tooltip labels
    tooltip: {
      prefixes: 'プレフィックス',
      suffixes: 'サフィックス',
      tier: 'T'
    }
  },
  pactspirits: {
    sectionTitle: 'パクトスピリット',
    level: 'レベル',
    selectPactspirit: 'パクトスピリットを選択',
    selectPlaceholder: 'パクトスピリットを選択...',
    searchPactspirits: 'パクトスピリットを検索...',
    noPactspiritsFound: '条件に一致するパクトスピリットが見つかりません。',
    microKismets: 'マイクロキスメット：',
    mediumKismets: 'ミディアムキスメット：',
    selectKismet: '{type}キスメットを選択',
    searchKismets: 'キスメットを検索...',
    loadingKismets: 'キスメットを読み込み中...',
    noKismetsFound: 'キスメットが見つかりません。',
    resetUndetermined: '未定運命をリセット',
    resetUndeterminedText: '未定運命を解除し、拡張スロットにインストールされたすべてのキスメットを削除します。',
    confirmContinue: '続行しますか？',
    cancel: 'キャンセル',
    reset: 'リセット',
    close: '閉じる',
    limitReached: '上限に達しました',
    cannotInstallKismet: 'キスメットをインストールできません',
    microLimitReached: 'マイクロキスメットの上限（9）に達しました！新しいものをインストールするには既存のマイクロ運命を削除してください。',
    mediumLimitReached: 'ミディアムキスメットの上限（4）に達しました！新しいものをインストールするには既存のミディアム運命を削除してください。',
    unlockFateSlots: '運命スロットを解放',
    unlockFateDesc: 'この未定運命スロットの拡張方法を選択：',
    fateOptionMicro: '{count}個のマイクロ運命スロット',
    fateOptionMedium: '{count}個のミディアム運命スロット',
    fateOptionMixed: '{medium}個のミディアムと{micro}個のマイクロ運命スロット',
    containsMultipleFates: '複数の運命が含まれています。',
    canBeExpanded: '複数のキスメットスロットに拡張可能です。',
    installMicroKismet: 'マイクロキスメットをインストール',
    installMediumKismet: 'ミディアムキスメットをインストール',
    installKismet: 'キスメットをインストール',
    undeterminedFateKismet: '不確定の運キスメット'
  },
  buildActions: {
    saveBuild: 'ビルドを保存',
    builds: 'ビルドリスト',
    newBuild: '+ 新規ビルド',
    noSavedBuilds: '保存されたビルドがありません',
    saveExport: '保存/エクスポート',
    exportJson: 'JSONとしてエクスポート',
    importJson: 'JSONからインポート',
    copyShareUrl: '共有URLをコピー',
    resetBuild: 'ビルドをリセット',
    resetConfirm: '現在のビルドをリセットしますか？保存されていない変更はすべて失われます。'
  },
  toasts: {
    buildSaved: 'ビルドを保存しました',
    newBuildCreated: '新規ビルドを作成しました',
    buildLoaded: 'ビルドを読み込みました',
    buildDeleted: 'ビルドを削除しました',
    buildReset: 'ビルドをリセットしました',
    importSuccess: 'ビルドを正常にインポートしました！',
    exportSuccess: 'ビルドをエクスポートしました',
    shareUrlCopied: '共有URLをクリップボードにコピーしました'
  },
  importModal: {
    title: 'ビルドをインポート',
    pasteJson: 'JSONを貼り付け',
    uploadFile: 'ファイルをアップロード',
    dragDrop: '.jsonファイルをここにドラッグ＆ドロップ',
    clickToSelect: 'クリックして選択',
    selected: '選択済み：',
    cancel: 'キャンセル',
    import: 'インポート',
    pastePlaceholder: 'ビルドJSONをここに貼り付け...',
    errorNoCode: 'ビルドJSONを貼り付けてください',
    errorNoFile: 'まずファイルを選択してください',
    errorInvalidJson: '無効なビルドJSON',
    errorWrongFileType: '.jsonファイルを選択してください',
    errorReadFailed: 'ファイルの読み取りに失敗しました'
  },
  settings: {
    title: '設定',
    language: '言語',
    done: '完了',
    comingSoon: '近日公開',
    close: '設定を閉じる'
  },
  divinity: {
    // Grid controls
    save: '保存',
    edit: '編集',
    inventory: 'インベントリ',
    reselect: '再選択',
    reset: 'リセット',
    // Context menu
    rotateCw: '時計回りに回転',
    rotateCcw: '反時計回りに回転',
    flipHorizontal: '水平方向に反転',
    flipVertical: '垂直方向に反転',
    editSlate: 'スレートを編集',
    removeSlate: 'スレートを削除',
    // Inventory drawer
    inventoryTitle: 'スレートインベントリ',
    noSlatesCrafted: 'スレートが未作成です',
    craftFirstSlate: '最初のスレートを作成',
    craftSlate: 'スレートを作成',
    // Slate card
    placed: '設置済み',
    affixes: 'アフィックス',
    affix: 'アフィックス',
    rareSlate: 'レアスレート',
    legendarySlate: 'レジェンダリースレート',
    deleteSlate: 'このスレートを削除しますか？',
    cancel: 'キャンセル',
    delete: '削除',
    unequip: '外す',
    // Crafting modal
    craftSlateTitle: 'スレートを作成',
    editSlateTitle: 'スレートを編集',
    craftLegendarySlateTitle: 'レジェンダリースレートを作成',
    editLegendarySlateTitle: 'レジェンダリースレートを編集',
    god: '神',
    shapeAndOrientation: '形状と向き',
    rotate: '回転',
    flipH: '水平反転',
    flipV: '垂直反転',
    affixesLabel: 'アフィックス',
    slot: 'スロット',
    legendaryTemplate: 'レジェンダリーテンプレート',
    fixedAffix: '固定アフィックス',
    saveChanges: '変更を保存',
    saveToInventory: 'インベントリに保存',
    cancelCrafting: 'キャンセル',
    // Node tooltip
    leftClickToAdd: '左クリック：ポイント追加',
    rightClickToRemove: '右クリック：ポイント削除',
    notableTalent: '顕著天賦',
    points: 'ポイント',
    noValidPlacement: '有効な配置が見つかりません。スペースを確保するために石板を並べ替えてください。',
    // Affix select
    selectAffix: 'アフィックスを選択...',
    searchAffix: '検索キーワードを入力...',
    noAffixMatches: '一致する結果がありません',
    // God names
    godNames: {
      Hunting: '狩猟の女神',
      Deception: '欺きの女神',
      Knowledge: '知識の女神',
      War: '戦争の神',
      Machines: '機械の神',
      Might: '力の神',
    },
    // Node types for affix display
    nodeTypes: {
      'Micro Talent': 'マイクロ才能',
      'Medium Talent': 'ミディアム才能',
      'Legendary Medium Talent': 'レジェンダリーミディアム才能',
      'Fixed': '固定'
    }
  },
  pactspiritCategories: {
    All: 'すべて',
    Attack: '攻撃',
    Erosion: '侵蝕',
    Spell: 'スペル',
    Persistent: '持続',
    Summon: '召喚',
    Survival: '生存',
    Cold: '冷気',
    Fire: '火炎',
    Lightning: '稲妻'
  },
  vorax: {
    tabName: 'ヴォラックス',
    editGear: 'ヴォラックス装備を編集',
    selectLimb: '部位を選択',
    loadingData: 'ヴォラックスデータを読み込み中...',
    baseAffix: 'ベースアフィックス',
    prefixes: 'プレフィックス',
    suffixes: 'サフィックス',
    none: 'なし',
    selectAffix: 'アフィックスを選択...',
    toggleLegendary: 'レジェンダリーモード切替',
    preview: 'プレビュー',
    unnamedItem: '名前なしアイテム',
    voraxGear: 'ヴォラックス装備',
    mods: 'モッド',
    noModsSelected: 'モッド未選択',
    selectLimbToPreview: 'プレビューする部位を選択',
    addToInventory: 'インベントリに追加',
    saveChanges: '変更を保存',
    limbs: {
      chest: '胸鎧',
      head: 'ヘルメット',
      hands: '手袋',
      legs: '脚鎧',
      neck: 'ネックレス',
      digits: '指輪',
      waist: 'ベルト'
    }
  },
  etherealPrism: {
    installPrismTitle: 'プリズムを設置 - ツリースロット {slot}',
    installEtherealPrismTitle: 'エセリアルプリズムを設置 - ツリースロット {slot}',
    installInverseImageTitle: '反転の写真を設置 - ツリースロット {slot}',
    etherealPrisms: 'エセリアルプリズム',
    etherealPrism: 'エセリアルプリズム',
    inverseImage: '反転の写真',
    showingType: '表示タイプ',
    noPrismsCrafted: 'プリズムが未作成です',
    craftFirstPrism: '最初のプリズムを作成',
    craftPrism: 'プリズムを作成',
    radius: '範囲',
    baseAffixLabel: 'ベースアフィックス',
    coreTalentLabel: 'コア天賦',
    equipped: '装備中',
    equippedElsewhere: '他で装備中',
    equip: '装備',
    edit: '編集',
    delete: '削除',
    craftPrismTitle: 'プリズムを作成',
    craftInverseImageTitle: '反転の写真を作成',
    editPrismTitle: 'プリズムを編集',
    etherealPrismTab: 'エセリアルプリズム',
    inverseImageTab: '反転の写真',
    baseItem: 'ベースアイテム',
    baseItemRequired: 'ベースアイテム *',
    baseItemCannotChange: '編集中はベースアイテムを変更できません',
    baseAffix: 'ベースアフィックス',
    baseAffixRequired: 'ベースアフィックス *',
    coreTalent: 'コア天賦',
    coreTalentRequired: 'コア天賦 *',
    selectBaseItem: 'ベースプリズムを選択',
    selectBaseAffix: 'ベースアフィックスを選択',
    noCoreTalent: 'コア天賦なし',
    coreTalentFixed: 'このプリズムは固定のコア天賦を持っています',
    randomAffixes: 'ランダムアフィックス',
    modValues: 'モッド数値',
    inverseImageNotAvailable: '反転の写真データは利用できません',
    radiusSlot: '範囲スロット',
    rareSlot: 'レアスロット',
    legendarySlot: 'レジェンダリースロット',
    radiusSlotDesc: '範囲モッドのみ',
    rareSlotDesc: 'レアモッドのみ',
    legendarySlotDesc: 'レジェンダリーモッドのみ',
    selectRadiusSlot: '-- 範囲スロットを選択 --',
    selectRareSlot: '-- レアスロットを選択 --',
    selectLegendarySlot: '-- レジェンダリースロットを選択 --',
    cancel: 'キャンセル',
    save: '保存',
    craft: '作成',
    installPrism: 'プリズムを設置',
    prismInstalledElsewhere: 'プリズムは他に設置されています',
    prismSlotsFull: 'プリズムスロットがいっぱいです',
    removePrism: 'プリズムを削除',
    cancelPlacement: 'キャンセル',
    additionalPointsFromPrism: 'プリズムモッドによる追加ポイント',
    prismAddition: 'プリズム追加効果',
    // Inverse Image Mod Names
    microTalentEffectRange: 'マイクロ天賦効果範囲',
    mediumTalentEffectRange: 'ミディアム天賦効果範囲',
    legendaryMediumTalentEffectRange: '伝説ミディアム天賦効果範囲'
  }
}
