/**
 * Build Planner Korean translations
 * Machine-assisted translations - Community review needed
 * These translations were generated with AI assistance and may not be
 * accurate for gaming terminology. Native speaker contributions welcome!
 * 26-2-19 검수됨. Pyo
 */
import type { BuildPlannerTranslations } from '../types'

export const buildplannerKo: BuildPlannerTranslations = {
  page: {
    backButton: '홈',
    buildName: '빌드 이름:',
    buildNamePlaceholder: '빌드 이름 입력'
  },
  hero: {
    sectionTitle: '히어로 특성',
    selectHero: '히어로 특성 선택',
    clickToSelect: '선택하려면 클릭',
    selectHeroToView: '히어로 특성을 선택하세요.',
    traitLevel: '레벨 {level}',
    changeHero: '히어로 특성 변경',
    lvl: 'Lv',
    noTraitsAvailable: '사용 가능한 특성 없음',
    selectHeroTitle: '히어로 특성 선택',
    searchHeroes: '히어로 특성 검색...',
    noHeroesFound: '히어로 특성을 찾을 수 없음',
    memoryOf: '{type}의 추억',
    clickToManageMemories: '클릭하여 추억 관리',
    clickToEquipMemory: '클릭하여 추억 장착',
    heroMemories: '히어로 특성 추억',
    noMemoriesCrafted: '아직 제작된 추억이 없습니다',
    craftFirstMemory: '첫 번째 추억 제작하기',
    noTypeMemories: '사용 가능한 {type} 추억 없음',
    craftMemory: '추억 제작',
    memoryNames: {
      Origin: '근원의 추억',
      Discipline: '자기 수호의 추억',
      Progress: '진격의 추억'
    },
    equipped: '장착됨',
    equip: '장착',
    delete: '삭제',
    editMemory: '추억 편집',
    memoryTypeLabel: '추억 유형',
    baseStat: '기본 속성',
    selectBaseStat: '기본 속성 선택...',
    fixedAffixes: '고유 옵션',
    randomAffixes: '랜덤 옵션',
    fixed: '고유',
    random: '랜덤',
    none: '없음',
    save: '저장',
    craft: '제작',
    cancel: '취소',
    cantChangeType: '편집 시 추억 유형을 변경할 수 없습니다',
    loadingMemories: '추억 데이터 로드 중...'
  },
  talentTree: {
    sectionTitle: '재능 보드',
    godTree: '재능 보드',
    clickToSelect: '선택하려면 클릭',
    classTree: '클래스 재능 보드',
    selectPreviousFirst: '먼저 이전 재능 보드를 선택하세요',
    treeNumber: '재능 보드 {number}',
    selectPrevious: '이전 선택',
    noTreeSelected: '선택된 재능 보드 없음',
    selectGodTree: '특성 재능 보드 구축을 시작하려면 사이드바에서 재능 보드를 선택하세요',
    selectGodTreeButton: '재능 보드 선택',
    divinity: '신격',
    slates: '석판',
    totalPoints: '총합 포인트',
    reselectTree: '재능 보드 재선택',
    reselectConfirmText: '다음 재능 보드와 할당된 포인트가 초기화됩니다:',
    confirmContinue: '계속하시겠습니까?',
    reselect: '재선택',
    resetPoints: '포인트 초기화',
    resetPointsText: '모든 포인트를 초기화합니다',
    totalPointsReset: '초기화될 총합 포인트:',
    cancel: '취소',
    reset: '초기화',
    selectSlotTitle: '{slot} 재능 보드 선택',
    searchTrees: '재능 보드 검색...',
    loading: '로딩 중...',
    noTreesSearch: '"{query}"와 일치하는 재능 보드를 찾을 수 없음',
    noTreesSlot: '이 슬롯에 사용 가능한 재능 보드 없음',
    selectNotableTitle: '{threshold}포인트 주목할 핵심 재능 선택',
    notableInstruction: '이 재능 보드에서 {threshold}포인트에 도달했습니다. 다음 핵심 재능 중 하나를 선택하세요:',
    selected: '선택됨',
    noNotablesAvailable: '이 재능 보드의 {threshold}포인트에서 사용 가능한 핵심 재능가 없습니다.'
  },
  skills: {
    sectionTitle: '스킬',
    activeSkills: '액티브 스킬',
    passiveSkills: '패시브 스킬',
    energy: '에너지',
    maxEnergy: '최대',
    skillsTab: '스킬',
    aurasTab: '오라',
    totalEnergy: '총 에너지:',
    overBudget: '(에너지 부족!)',
    resetSkills: '스킬 슬롯 초기화',
    resetSkillsConfirm: '액티브와 오라, 보조 스킬 전부 초기화합니다.',
    confirmContinue: '계속하시겠습니까?',
    selectActiveSkill: '액티브 스킬 선택',
    selectPassiveSkill: '패시브 스킬 선택',
    searchSkills: '스킬 검색...',
    noSkillsFound: '스킬을 찾을 수 없음',
    selectSupport: '{type} 선택 (슬롯 {slot})',
    searchSupports: '보조 검색...',
    noSupportsAvailable: '사용 가능한 보조 없음',
    clearSlot: '슬롯 비우기',
    cancel: '취소',
    reset: '초기화',
    removeSkill: '스킬을 삭제하시겠습니까?',
    removeSkillConfirm: '이 스킬을 삭제하면 할당된 {count}개의 보조 스킬도 모두 삭제됩니다. 계속하시겠습니까?',
    removeAll: '모두 삭제',
    clickToSelectActive: '클릭하여 액티브 스킬 선택',
    clickToSelectPassive: '클릭하여 패시브 스킬 선택',
    supportTypes: {
      activation: '촉발체 / 보조',
      magnificent: '부귀 / 보조',
      noble: '숭고 / 보조',
      support: '보조',
      activationShort: '촉발',
      magnificentShort: '부귀',
      nobleShort: '숭고',
      supportShort: '보조'
    },
    stats: {
      mainStat: '주요 능력치',
      manaCost: '마나 소모량',
      castSpeed: '사용 속도',
      addedDamage: '추가 대미지',
      sealedMana: '봉인된 마나'
    }
  },
  gear: {
    sectionTitle: '장비',
    // Inventory
    inventory: '인벤토리 ({count})',
    addNewItem: '새 아이템 추가',
    noItemsCrafted: '제작된 아이템이 없습니다',
    craftFirstItem: '첫 번째 아이템 제작',
    slots: '{filled}/10 슬롯',
    // Slot names
    slotsNames: {
      helmet: '투구',
      chest: '흉갑',
      gloves: '장갑',
      boots: '부츠',
      belt: '벨트',
      ring1: '반지 1',
      ring2: '반지 2',
      necklace: '목걸이',
      mainHand: '무기 1',
      offHand: '무기 2'
    },
    // Crafting modal
    craftGear: '장비 제작',
    editGear: '장비 편집',
    rarity: {
      Rare: '레어',
      Legendary: '레전드'
    },
    rarityCannotChange: '편집 중에는 레어도를 변경할 수 없습니다',
    // Form labels
    itemType: '아이템 유형',
    selectItemType: '아이템 유형 선택...',
    baseItem: '기본 아이템',
    selectBaseItem: '기본 아이템 선택...',
    itemLevel: '레벨 조건 {level}',
    loadingGearData: '장비 데이터 로드 중...',
    beltBlend: '벨트 조향',
    towerSequence: '타워 시퀀스',
    sweetDreamAffix: '해몽 기본 옵션',
    baseAffix: '기본 옵션',
    baseAffixPriceless: '없음',
    corrosionImplicit: '침식 기본 옵션',
    corrosionDisabled: '(비활성화 - 모드가 부식됨)',
    prefixes: '메인 옵션',
    suffixes: '서브 옵션',
    corroded: '{count}/2 부식됨',
    none: '없음',
    // Preview
    preview: '미리보기',
    selectOptionsToPreview: '미리보기할 옵션 선택',
    unnamedItem: '이름 없는 아이템',
    addToInventory: '인벤토리에 추가',
    saveChanges: '변경사항 저장',
    // Actions
    equip: '장착',
    unequip: '해제',
    edit: '편집',
    delete: '삭제',
    equipped: '장착됨',
    clickToManage: '클릭하여 관리',
    // Category display names
    categories: {
      helmet: '방어구 - 투구',
      chest_armor: '방어구 - 흉갑',
      gloves: '방어구 - 장갑',
      boots: '방어구 - 부츠',
      shield: '방패',
      trinket: '장신구',
      one_handed: '한손 무기',
      two_handed: '양손 무기'
    },
    // Sub-type display names
    subTypes: {
      // Helmets
      str_helmet: 'STR 투구',
      dex_helmet: 'DEX 투구',
      int_helmet: 'INT 투구',
      // Chest
      str_chest_armor: 'STR 흉갑',
      dex_chest_armor: 'DEX 흉갑',
      int_chest_armor: 'INT 흉갑',
      // Gloves
      str_gloves: 'STR 장갑',
      dex_gloves: 'DEX 장갑',
      int_gloves: 'INT 장갑',
      // Boots
      str_boots: 'STR 부츠',
      dex_boots: 'DEX 부츠',
      int_boots: 'INT 부츠',
      // Shields
      str_shield: 'STR 방패',
      dex_shield: 'DEX 방패',
      int_shield: 'INT 방패',
      // Trinkets
      belt: '벨트',
      necklace: '목걸이',
      ring: '반지',
      spirit_ring: '영혼 반지',
      // 1H Weapons
      cane: '한손 지팡이',
      claw: '클로',
      dagger: '단검',
      'one-handed_axe': '한손 도끼',
      'one-handed_hammer': '한손 핸머',
      'one-handed_sword': '한손 검',
      pistol: '권총',
      rod: '영혼 지팡이',
      scepter: '마력 지팡이',
      wand: '마법 지팡이',
      // 2H Weapons
      bow: '활',
      crossbow: '석궁',
      cudgel: '무사의 스틱',
      fire_cannon: '화포',
      musket: '머스킷',
      tin_staff: '주석 지팡이',
      'two-handed_axe': '양손 도끼',
      'two-handed_hammer': '양손 핸머',
      'two-handed_sword': '양손 검'
    },
    // Tooltip labels
    tooltip: {
      prefixes: '메인 옵션',
      suffixes: '서브 옵션',
      tier: 'T'
    }
  },
  pactspirits: {
    sectionTitle: '전투 정령',
    level: '레벨',
    selectPactspirit: '전투 정령 선택',
    selectPlaceholder: '전투 정령 선택...',
    searchPactspirits: '전투 정령 검색...',
    noPactspiritsFound: '조건에 맞는 전투 정령을 찾을 수 없습니다.',
    microKismets: '하위 숙명:',
    mediumKismets: '중위 숙명:',
    selectKismet: '{type} 숙명 선택',
    searchKismets: '숙명 검색...',
    loadingKismets: '숙명 로딩 중...',
    noKismetsFound: '숙명을 찾을 수 없습니다.',
    resetUndetermined: '미정 숙명 초기화',
    resetUndeterminedText: '미정 숙명을 해제하고 확장 슬롯에 설치된 모든 숙명을 제거합니다.',
    confirmContinue: '계속하시겠습니까?',
    cancel: '취소',
    reset: '초기화',
    close: '닫기',
    limitReached: '한도 도달',
    cannotInstallKismet: '숙명을 설치할 수 없습니다',
    microLimitReached: '하위 숙명 한도(9)에 도달했습니다! 새로운 것을 설치하려면 기존 하위 숙명을 제거하세요.',
    mediumLimitReached: '중위 숙명 한도(4)에 도달했습니다! 새로운 것을 설치하려면 기존 중위 숙명을 제거하세요.',
    unlockFateSlots: '숙명 슬롯 해제',
    unlockFateDesc: '이 미정 숙명 슬롯의 확장 방법을 선택하세요:',
    fateOptionMicro: '{count}개 하위 숙명 슬롯',
    fateOptionMedium: '{count}개 중위 숙명 슬롯',
    fateOptionMixed: '{medium}개 중위 및 {micro}개 하위 숙명 슬롯',
    containsMultipleFates: '여러 운이 있습니다.',
    canBeExpanded: '여러 숙명 슬롯으로 확장할 수 있습니다.',
    installMicroKismet: '하위 숙명 설치',
    installMediumKismet: '중위 숙명 설치',
    installKismet: '숙명 설치',
    undeterminedFateKismet: '미정 숙명'
  },
  buildActions: {
    saveBuild: '빌드 저장',
    builds: '빌드 목록',
    newBuild: '+ 새 빌드',
    noSavedBuilds: '저장된 빌드 없음',
    saveExport: '저장/내보내기',
    exportJson: 'JSON으로 내보내기',
    importJson: 'JSON에서 가져오기',
    copyShareUrl: '공유 URL 복사',
    resetBuild: '빌드 초기화',
    resetConfirm: '현재 빌드를 초기화하시겠습니까? 저장하지 않은 변경사항이 모두 삭제됩니다.'
  },
  toasts: {
    buildSaved: '빌드 저장 완료',
    newBuildCreated: '새 빌드 생성됨',
    buildLoaded: '빌드 불러오기 완료',
    buildDeleted: '빌드 삭제됨',
    buildReset: '빌드 초기화됨',
    importSuccess: '빌드를 성공적으로 가져왔습니다!',
    exportSuccess: '빌드 내보내기 완료',
    shareUrlCopied: '공유 URL이 클립보드에 복사되었습니다'
  },
  importModal: {
    title: '빌드 가져오기',
    pasteJson: 'JSON 붙여넣기',
    uploadFile: '파일 업로드',
    dragDrop: '.json 파일을 여기에 드래그 앤 드롭하세요',
    clickToSelect: '클릭하여 선택',
    selected: '선택됨:',
    cancel: '취소',
    import: '가져오기',
    pastePlaceholder: '빌드 JSON을 여기에 붙여넣기...',
    errorNoCode: '빌드 JSON을 붙여넣으세요',
    errorNoFile: '먼저 파일을 선택하세요',
    errorInvalidJson: '유효하지 않은 빌드 JSON',
    errorWrongFileType: '.json 파일을 선택하세요',
    errorReadFailed: '파일 읽기 실패'
  },
  settings: {
    title: '설정',
    language: '언어',
    done: '완료',
    comingSoon: '곧 출시',
    close: '설정 닫기'
  },
  divinity: {
    // Grid controls
    save: '저장',
    edit: '수정',
    inventory: '인벤토리',
    reselect: '재선택',
    reset: '초기화',
    // Context menu
    rotateCw: '시계 방향 회전',
    rotateCcw: '반시계 방향 회전',
    flipHorizontal: '수평 뒤집기',
    flipVertical: '수직 뒤집기',
    editSlate: '신격 석판 수정',
    removeSlate: '신격 석판 제거',
    // Inventory drawer
    inventoryTitle: '신격 석판 인벤토리',
    noSlatesCrafted: '제작된 신격 석판 없음',
    craftFirstSlate: '첫 신격 석판 제작',
    craftSlate: '신격 석판 제작',
    // Slate card
    placed: '장착됨',
    affixes: '접미사',
    affix: '접미사',
    rareSlate: '레어 신격 석판',
    legendarySlate: '레전드 신격 석판',
    deleteSlate: '이 신격 석판를 삭제하시겠습니까?',
    cancel: '취소',
    delete: '삭제',
    unequip: '해제',
    // Crafting modal
    craftSlateTitle: '신격 석판 제작',
    editSlateTitle: '신격 석판 수정',
    craftLegendarySlateTitle: '레전드 신격 석판 제작',
    editLegendarySlateTitle: '레전드 신격 석판 수정',
    god: '신',
    shapeAndOrientation: '형태 및 방향',
    rotate: '회전',
    flipH: '수평 뒤집기',
    flipV: '수직 뒤집기',
    affixesLabel: '접미사',
    slot: '슬롯',
    legendaryTemplate: '레전드 템플릿',
    fixedAffix: '고정 접미사',
    saveChanges: '변경사항 저장',
    saveToInventory: '인벤토리에 저장',
    cancelCrafting: '취소',
    // Node tooltip
    leftClickToAdd: '좌클릭: 포인트 추가',
    rightClickToRemove: '우클릭: 포인트 제거',
    notableTalent: '주목할 핵심 재능',
    points: '포인트',
    noValidPlacement: '유효한 배치 위치를 찾을 수 없습니다. 공간을 확보하려면 석판을 재배열하세요.',
    // Affix select
    selectAffix: '접두사 선택...',
    searchAffix: '검색어 입력...',
    noAffixMatches: '일치하는 결과 없음',
    // God names
    godNames: {
      Hunting: '사냥의 여신',
      Deception: '기만의 여신',
      Knowledge: '지식의 여신',
      War: '전쟁의 신',
      Machines: '기계의 신',
      Might: '힘의 신',
    },
    // Node types for affix display
    nodeTypes: {
      'Micro Talent': '하위 재능',
      'Medium Talent': '중위 재능',
      'Legendary Medium Talent': '레전드 중위 재능',
      'Fixed': '고정'
    }
  },
  pactspiritCategories: {
    All: '전체',
    Attack: '공격',
    Erosion: '침식',
    Spell: '주문',
    Persistent: '지속',
    Summon: '소환',
    Survival: '생존',
    Cold: '냉기',
    Fire: '화염',
    Lightning: '번개'
  },
  vorax: {
    tabName: '블러드 러스트',
    editGear: '블러드 러스트 장비 편집',
    selectLimb: '부위 선택',
    loadingData: '블러드 러스트 데이터 로드 중...',
    baseAffix: '기본 접미사',
    prefixes: '접두사',
    suffixes: '접미사',
    none: '없음',
    selectAffix: '접미사 선택...',
    toggleLegendary: '레전드 모드 전환',
    preview: '미리보기',
    unnamedItem: '이름 없는 아이템',
    voraxGear: '블러드 러스트 장비',
    mods: '모드',
    noModsSelected: '모드 미선택',
    selectLimbToPreview: '미리보기할 부위 선택',
    addToInventory: '인벤토리에 추가',
    saveChanges: '변경사항 저장',
    limbs: {
      chest: '흉갑',
      head: '투구',
      hands: '장갑',
      legs: '각반',
      neck: '목걸이',
      digits: '반지',
      waist: '벨트'
    }
  },
  etherealPrism: {
    installPrismTitle: '프리즘 장착 - 재능 보드 슬롯 {slot}',
    installEtherealPrismTitle: '제노 프리즘 장착 - 재능 보드 슬롯 {slot}',
    installInverseImageTitle: '역상 장착 - 재능 보드 슬롯 {slot}',
    etherealPrisms: '제노 프리즘',
    etherealPrism: '제노 프리즘',
    inverseImage: '역상',
    showingType: '표시 유형',
    noPrismsCrafted: '제작된 프리즘 없음',
    craftFirstPrism: '첫 프리즘 제작',
    craftPrism: '프리즘 제작',
    radius: '범위',
    baseAffixLabel: '기본 접미사',
    coreTalentLabel: '핵심 재능',
    equipped: '장착됨',
    equippedElsewhere: '다른 위치에 장착됨',
    equip: '장착',
    edit: '편집',
    delete: '삭제',
    craftPrismTitle: '프리즘 제작',
    craftInverseImageTitle: '역상 제작',
    editPrismTitle: '프리즘 편집',
    etherealPrismTab: '제노 프리즘',
    inverseImageTab: '역상',
    baseItem: '기본 아이템',
    baseItemRequired: '기본 아이템 *',
    baseItemCannotChange: '편집 시 기본 아이템을 변경할 수 없습니다',
    baseAffix: '기본 접미사',
    baseAffixRequired: '기본 접미사 *',
    coreTalent: '코어 핵심 재능',
    coreTalentRequired: '코어 핵심 재능 *',
    selectBaseItem: '기본 프리즘 선택',
    selectBaseAffix: '기본 접미사 선택',
    noCoreTalent: '사용 가능한 코어 핵심 재능 없음',
    coreTalentFixed: '이 프리즘은 고정된 코어 핵심 재능를 가지고 있습니다',
    randomAffixes: '랜덤 접미사',
    modValues: '속성 값',
    inverseImageNotAvailable: '역상 데이터를 사용할 수 없습니다',
    radiusSlot: '범위 슬롯',
    rareSlot: '레어 슬롯',
    legendarySlot: '레전드 슬롯',
    radiusSlotDesc: '범위 모드만',
    rareSlotDesc: '레어 모드만',
    legendarySlotDesc: '레전드 모드만',
    selectRadiusSlot: '-- 범위 슬롯 선택 --',
    selectRareSlot: '-- 레어 슬롯 선택 --',
    selectLegendarySlot: '-- 레전드 슬롯 선택 --',
    cancel: '취소',
    save: '저장',
    craft: '제작',
    installPrism: '프리즘 장착',
    prismInstalledElsewhere: '프리즘이 다른 위치에 장착됨',
    prismSlotsFull: '프리즘 슬롯 가득',
    removePrism: '프리즘 제거',
    cancelPlacement: '취소',
    additionalPointsFromPrism: '프리즘 모드 추가 포인트',
    prismAddition: '프리즘 추가 효과',
    // Inverse Image Mod Names
    microTalentEffectRange: '하위 핵심 재능 효과 범위',
    mediumTalentEffectRange: '중위 핵심 재능 효과 범위',
    legendaryMediumTalentEffectRange: '레전드 중위 핵심 재능 효과 범위'
  }
}
