/**
 * Build Planner Russian translations
 * Machine-assisted translations - Community review needed
 * These translations were generated with AI assistance and may not be
 * accurate for gaming terminology. Native speaker contributions welcome!
 */
import type { BuildPlannerTranslations } from '../types'

export const buildplannerRu: BuildPlannerTranslations = {
  page: {
    backButton: 'ГЛАВНАЯ',
    buildName: 'Название сборки:',
    buildNamePlaceholder: 'Введите название сборки'
  },
  hero: {
    sectionTitle: 'ГЕРОЙ',
    selectHero: 'Нажмите чтобы выбрать героя',
    clickToSelect: 'Нажмите чтобы выбрать',
    selectHeroToView: 'Выберите героя чтобы просмотреть и выбрать черты',
    traitLevel: 'Уровень {level}',
    changeHero: 'Сменить героя',
    lvl: 'Ур',
    noTraitsAvailable: 'Нет доступных черт',
    selectHeroTitle: 'Выбор героя',
    searchHeroes: 'Поиск героев...',
    noHeroesFound: 'Герои не найдены',
    memoryOf: 'Память {type}',
    clickToManageMemories: 'Нажмите для управления воспоминаниями',
    clickToEquipMemory: 'Нажмите чтобы экипировать воспоминание',
    heroMemories: 'Воспоминания героя',
    noMemoriesCrafted: 'Воспоминания ещё не созданы',
    craftFirstMemory: 'Создайте первое воспоминание',
    noTypeMemories: 'Нет доступных воспоминаний типа {type}',
    craftMemory: 'Создать воспоминание',
    memoryNames: {
      Origin: 'Память источника',
      Discipline: 'Память сохранения',
      Progress: 'Память стремления'
    },
    equipped: 'Экипировано',
    equip: 'Надеть',
    delete: 'Удалить',
    editMemory: 'Редактировать память',
    memoryTypeLabel: 'Тип памяти',
    baseStat: 'Базовый параметр',
    selectBaseStat: 'Выберите базовый параметр...',
    fixedAffixes: 'Присущий аффикс',
    randomAffixes: 'Случайный аффикс',
    fixed: 'Присущий',
    random: 'Случайный',
    none: 'Нет',
    save: 'Сохранить',
    craft: 'Создать',
    cancel: 'Отмена',
    cantChangeType: 'Тип памяти нельзя изменить при редактировании',
    loadingMemories: 'Загрузка данных памяти...'
  },
  talentTree: {
    sectionTitle: 'ДРЕВО ТАЛАНТОВ',
    godTree: 'БОЖЕСТВЕННОЕ ДРЕВО',
    clickToSelect: 'Нажмите чтобы выбрать',
    classTree: 'КЛАССОВОЕ ДРЕВО',
    selectPreviousFirst: 'Сначала выберите предыдущее',
    treeNumber: 'ДРЕВО {number}',
    selectPrevious: 'Выбрать предыдущее',
    noTreeSelected: 'Древо не выбрано',
    selectGodTree: 'Выберите Божественное Древо из боковой панели чтобы начать строить ваше древо талантов',
    selectGodTreeButton: 'Выбрать Божественное Древо',
    divinity: 'Божественность',
    slates: 'Таблички',
    totalPoints: 'Всего очков',
    reselectTree: 'Перевыбрать древо',
    reselectConfirmText: 'Это сбросит следующие деревья и их распределённые очки:',
    confirmContinue: 'Вы уверены что хотите продолжить?',
    reselect: 'Перевыбрать',
    resetPoints: 'Сбросить очки',
    resetPointsText: 'Это сбросит все очки в',
    totalPointsReset: 'Очки для сброса:',
    cancel: 'Отмена',
    reset: 'Сброс',
    selectSlotTitle: 'Выбрать {slot} древо',
    searchTrees: 'Поиск деревьев...',
    loading: 'Загрузка...',
    noTreesSearch: 'Деревья по запросу "{query}" не найдены',
    noTreesSlot: 'Нет доступных деревьев для этого слота',
    selectNotableTitle: 'Выбрать {threshold}-очковый заметный талант',
    notableInstruction: 'Вы достигли {threshold} очков в этом древе. Выберите один из следующих заметных талантов:',
    selected: 'Выбрано',
    noNotablesAvailable: 'Нет доступных заметных талантов на {threshold} очках для этого древа.'
  },
  skills: {
    sectionTitle: 'НАВЫКИ',
    activeSkills: 'Активные навыки',
    passiveSkills: 'Пассивные навыки',
    energy: 'Энергия',
    maxEnergy: 'макс',
    skillsTab: 'Навыки',
    aurasTab: 'Ауры',
    totalEnergy: 'Всего энергии:',
    overBudget: '(Превышен бюджет!)',
    resetSkills: 'Сбросить навыки',
    resetSkillsConfirm: 'Это сбросит все активные навыки и ауры, включая их камни поддержки.',
    confirmContinue: 'Вы уверены что хотите продолжить?',
    selectActiveSkill: 'Выбрать активный навык',
    selectPassiveSkill: 'Выбрать пассивный навык',
    searchSkills: 'Поиск навыков...',
    noSkillsFound: 'Навыки не найдены',
    selectSupport: 'Выбрать {type} (Слот {slot})',
    searchSupports: 'Поиск поддержки...',
    noSupportsAvailable: 'Нет доступной поддержки',
    clearSlot: 'Очистить слот',
    cancel: 'Отмена',
    reset: 'Сброс',
    removeSkill: 'Удалить навык?',
    removeSkillConfirm: 'Удаление этого навыка также очистит все {count} навык(ов) поддержки, назначенных ему. Вы уверены?',
    removeAll: 'Удалить всё',
    clickToSelectActive: 'Нажмите чтобы выбрать активный навык',
    clickToSelectPassive: 'Нажмите чтобы выбрать пассивный навык',
    supportTypes: {
      activation: 'Активация / Поддержка',
      magnificent: 'Великолепная / Поддержка',
      noble: 'Благородная / Поддержка',
      support: 'Поддержка',
      activationShort: 'Активация',
      magnificentShort: 'Великолепная',
      nobleShort: 'Благородная',
      supportShort: 'Поддержка'
    },
    stats: {
      mainStat: 'Основная характеристика',
      manaCost: 'Затраты маны',
      castSpeed: 'Скорость применения',
      addedDamage: 'Добавленный урон',
      sealedMana: 'Запечатанная мана'
    }
  },
  gear: {
    sectionTitle: 'СНАРЯЖЕНИЕ',
    // Inventory
    inventory: 'Инвентарь ({count})',
    addNewItem: 'Добавить новый предмет',
    noItemsCrafted: 'Предметы еще не созданы',
    craftFirstItem: 'Создать первый предмет',
    slots: '{filled}/10 слотов',
    // Slot names
    slotsNames: {
      helmet: 'Шлем',
      chest: 'Нагрудник',
      gloves: 'Перчатки',
      boots: 'Сапоги',
      belt: 'Пояс',
      ring1: 'Кольцо 1',
      ring2: 'Кольцо 2',
      necklace: 'Ожерелье',
      mainHand: 'Оружие 1',
      offHand: 'Оружие 2'
    },
    // Crafting modal
    craftGear: 'Создать снаряжение',
    editGear: 'Редактировать снаряжение',
    rarity: {
      Rare: 'Редкий',
      Legendary: 'Легендарный'
    },
    rarityCannotChange: 'Редкость нельзя изменить при редактировании',
    // Form labels
    itemType: 'Тип предмета',
    selectItemType: 'Выберите тип предмета...',
    baseItem: 'Базовый предмет',
    selectBaseItem: 'Выберите базовый предмет...',
    itemLevel: '{level} ур.',
    loadingGearData: 'Загрузка данных снаряжения...',
    beltBlend: 'Смесь пояса',
    towerSequence: 'TOWER последовательность',
    sweetDreamAffix: 'Аффикс сладкого сна',
    baseAffix: 'Базовый аффикс',
    baseAffixPriceless: 'Бесценный',
    corrosionImplicit: 'Коррозионный имплицит',
    corrosionDisabled: '(отключено - моды корродированы)',
    prefixes: 'Префиксы',
    suffixes: 'Суффиксы',
    corroded: '{count}/2 корродировано',
    none: 'Нет',
    // Preview
    preview: 'Предпросмотр',
    selectOptionsToPreview: 'Выберите опции для предпросмотра',
    unnamedItem: 'Безымянный предмет',
    addToInventory: 'Добавить в инвентарь',
    saveChanges: 'Сохранить изменения',
    // Actions
    equip: 'Экипировать',
    unequip: 'Снять',
    edit: 'Редактировать',
    delete: 'Удалить',
    equipped: 'Э',
    clickToManage: 'Нажмите для управления',
    // Category display names
    categories: {
      helmet: 'Доспехи - Шлем',
      chest_armor: 'Доспехи - Нагрудник',
      gloves: 'Доспехи - Перчатки',
      boots: 'Доспехи - Сапоги',
      shield: 'Щит',
      trinket: 'Аксессуар',
      one_handed: 'Одноручное оружие',
      two_handed: 'Двуручное оружие'
    },
    // Sub-type display names
    subTypes: {
      // Helmets
      str_helmet: 'СИЛ шлем',
      dex_helmet: 'ЛОВ шлем',
      int_helmet: 'ИНТ шлем',
      // Chest
      str_chest_armor: 'СИЛ нагрудник',
      dex_chest_armor: 'ЛОВ нагрудник',
      int_chest_armor: 'ИНТ нагрудник',
      // Gloves
      str_gloves: 'СИЛ перчатки',
      dex_gloves: 'ЛОВ перчатки',
      int_gloves: 'ИНТ перчатки',
      // Boots
      str_boots: 'СИЛ сапоги',
      dex_boots: 'ЛОВ сапоги',
      int_boots: 'ИНТ сапоги',
      // Shields
      str_shield: 'СИЛ щит',
      dex_shield: 'ЛОВ щит',
      int_shield: 'ИНТ щит',
      // Trinkets
      belt: 'Пояс',
      necklace: 'Ожерелье',
      ring: 'Кольцо',
      spirit_ring: 'Кольцо духа',
      // 1H Weapons
      cane: 'Трость',
      claw: 'Коготь',
      dagger: 'Кинжал',
      'one-handed_axe': 'Одноручный топор',
      'one-handed_hammer': 'Одноручный молот',
      'one-handed_sword': 'Одноручный меч',
      pistol: 'Пистолет',
      rod: 'Жезл',
      scepter: 'Скипетр',
      wand: 'Волшебная палочка',
      // 2H Weapons
      bow: 'Лук',
      crossbow: 'Арбалет',
      cudgel: 'Дубина',
      fire_cannon: 'Огненная пушка',
      musket: 'Мушкет',
      tin_staff: 'Оловянный посох',
      'two-handed_axe': 'Двуручный топор',
      'two-handed_hammer': 'Двуручный молот',
      'two-handed_sword': 'Двуручный меч'
    },
    // Tooltip labels
    tooltip: {
      prefixes: 'Префиксы',
      suffixes: 'Суффиксы',
      tier: 'T'
    }
  },
  pactspirits: {
    sectionTitle: 'ДУХИ СОГЛАШЕНИЯ',
    level: 'Уровень',
    selectPactspirit: 'Выбрать духа',
    selectPlaceholder: 'Выберите духа...',
    searchPactspirits: 'Поиск духов...',
    noPactspiritsFound: 'Духи по заданным критериям не найдены.',
    microKismets: 'Малые кисметы:',
    mediumKismets: 'Средние кисметы:',
    selectKismet: 'Выбрать {type} кисмет',
    searchKismets: 'Поиск кисметов...',
    loadingKismets: 'Загрузка кисметов...',
    noKismetsFound: 'Кисметы не найдены.',
    resetUndetermined: 'Сбросить неопределённую судьбу',
    resetUndeterminedText: 'Это снимет неопределённую судьбу и удалит все кисметы, установленные в её расширенных слотах.',
    confirmContinue: 'Вы уверены что хотите продолжить?',
    cancel: 'Отмена',
    reset: 'Сброс',
    close: 'Закрыть',
    limitReached: 'Достигнут предел',
    cannotInstallKismet: 'Невозможно установить кисмет',
    microLimitReached: 'Достигнут предел малых кисметов (9)! Удалите существующую малую судьбу для установки новой.',
    mediumLimitReached: 'Достигнут предел средних кисметов (4)! Удалите существующую среднюю судьбу для установки новой.',
    unlockFateSlots: 'Разблокировать слоты судьбы',
    unlockFateDesc: 'Выберите как расширить этот слот неопределённой судьбы:',
    fateOptionMicro: '{count} малый слот судьбы',
    fateOptionMedium: '{count} средний слот судьбы',
    fateOptionMixed: '{medium} средних и {micro} малых слотов судьбы',
    containsMultipleFates: 'Содержит несколько судеб.',
    canBeExpanded: 'Можно расширить до нескольких слотов кисмета.',
    installMicroKismet: 'Установить малый кисмет',
    installMediumKismet: 'Установить средний кисмет',
    installKismet: 'Установить кисмет',
    undeterminedFateKismet: 'Кисмет неопределенной судьбы'
  },
  buildActions: {
    saveBuild: 'Сохранить сборку',
    builds: 'Сборки',
    newBuild: '+ Новая сборка',
    noSavedBuilds: 'Нет сохраненных сборок',
    saveExport: 'Сохранить/Экспорт',
    exportJson: 'Экспортировать как JSON',
    importJson: 'Импортировать из JSON',
    copyShareUrl: 'Копировать URL для обмена',
    resetBuild: 'Сбросить сборку',
    resetConfirm: 'Сбросить текущую сборку? Все несохраненные изменения будут потеряны.',
    saveModal: {
      title: 'Сохранить сборку',
      warning: 'Это сохраняет только в локальное хранилище браузера. Используйте экспорт для создания переносимого файла.',
      cloudInfo: 'Эта сборка будет сохранена в облаке. Текущий лимит - {limit} сборки на пользователя.',
      cloudToggle: 'Активировать облачное сохранение ({count}/{limit})',
      loginPrompt: 'Хотите сохранить свои сборки в облаке?',
      loginLink: 'Войдите',
      loginPromptEnd: 'чтобы использовать эту функцию.',
      buildName: 'Название сборки',
      placeholder: 'Введите название сборки...',
      errorNoName: 'Пожалуйста, введите название сборки',
      errorSaveFailed: 'Не удалось сохранить сборку. Возможно, хранилище заполнено.',
      errorCloudLimit: 'Достигнут лимит облачных сборок ({limit}). Удалите облачную сборку, чтобы сохранить больше.',
      errorCloudSaveFailed: 'Не удалось сохранить в облако. Пожалуйста, попробуйте снова.',
      cancel: 'Отмена',
      save: 'Сохранить'
    },
    deleteModal: {
      title: 'Удалить сборку',
      warning: 'Вы уверены, что хотите удалить "{name}"?',
      irreversible: 'Это действие нельзя отменить.',
      cancel: 'Отмена',
      confirm: 'Удалить'
    }
  },
  toasts: {
    buildSaved: 'Сборка сохранена успешно',
    saveSuccessCloud: 'Сборка "{name}" сохранена в облако!',
    newBuildCreated: 'Создана новая сборка',
    buildLoaded: 'Сборка загружена',
    buildDeleted: 'Сборка удалена',
    deleteSuccessCloud: 'Облачная сборка "{name}" удалена',
    deleteFailedCloud: 'Не удалось удалить облачную сборку',
    loadFailed: 'Не удалось загрузить сборку',
    buildReset: 'Сборка сброшена',
    importSuccess: 'Сборка успешно импортирована!',
    exportSuccess: 'Сборка экспортирована',
    shareUrlCopied: 'URL для обмена скопирован в буфер обмена'
  },
  importModal: {
    title: 'Импорт сборки',
    pasteJson: 'Вставить JSON',
    uploadFile: 'Загрузить файл',
    dragDrop: 'Перетащите .json файл сюда',
    clickToSelect: 'нажмите чтобы выбрать',
    selected: 'Выбрано:',
    cancel: 'Отмена',
    import: 'Импорт',
    pastePlaceholder: 'Вставьте JSON сборки здесь...',
    errorNoCode: 'Вставьте JSON сборки',
    errorNoFile: 'Сначала выберите файл',
    errorInvalidJson: 'Недействительный JSON сборки',
    errorWrongFileType: 'Выберите .json файл',
    errorReadFailed: 'Ошибка чтения файла'
  },
  settings: {
    title: 'Настройки',
    language: 'Язык',
    done: 'Готово',
    comingSoon: 'Скоро',
    close: 'Закрыть настройки'
  },
  divinity: {
    // Grid controls
    save: 'Сохранить',
    edit: 'Изменить',
    inventory: 'Инвентарь',
    reselect: 'Перевыбрать',
    reset: 'Сбросить',
    // Context menu
    rotateCw: 'Повернуть по часовой',
    rotateCcw: 'Повернуть против часовой',
    flipHorizontal: 'Отразить горизонтально',
    flipVertical: 'Отразить вертикально',
    editSlate: 'Изменить сланец',
    removeSlate: 'Убрать сланец',
    // Inventory drawer
    inventoryTitle: 'Инвентарь сланцев',
    noSlatesCrafted: 'Сланцы еще не созданы',
    craftFirstSlate: 'Создать первый сланец',
    craftSlate: 'Создать сланец',
    // Slate card
    placed: 'Установлен',
    affixes: 'модификаторов',
    affix: 'модификатор',
    rareSlate: 'Редкий сланец',
    legendarySlate: 'Легендарный сланец',
    deleteSlate: 'Удалить этот сланец?',
    cancel: 'Отмена',
    delete: 'Удалить',
    unequip: 'Снять',
    // Crafting modal
    craftSlateTitle: 'Создать сланец',
    editSlateTitle: 'Изменить сланец',
    craftLegendarySlateTitle: 'Создать легендарный сланец',
    editLegendarySlateTitle: 'Изменить легендарный сланец',
    god: 'Бог',
    shapeAndOrientation: 'Форма и ориентация',
    rotate: 'Повернуть',
    flipH: 'Отразить гор.',
    flipV: 'Отразить верт.',
    affixesLabel: 'Модификаторы',
    slot: 'Слот',
    legendaryTemplate: 'Легендарный шаблон',
    fixedAffix: 'Фиксированный модификатор',
    saveChanges: 'Сохранить изменения',
    saveToInventory: 'Сохранить в инвентарь',
    cancelCrafting: 'Отмена',
    // Node tooltip
    leftClickToAdd: 'ЛКМ: Добавить очко',
    rightClickToRemove: 'ПКМ: Убрать очко',
    notableTalent: 'Заметный талант',
    points: 'очков',
    noValidPlacement: 'Не найдено подходящего места. Переставьте скрижали, чтобы освободить место.',
    // Affix select
    selectAffix: 'Выберите аффикс...',
    searchAffix: 'Введите для поиска...',
    noAffixMatches: 'Нет совпадений',
    // God names
    godNames: {
      Hunting: 'Богиня Охоты',
      Deception: 'Богиня Обмана',
      Knowledge: 'Богиня Знаний',
      War: 'Бог Войны',
      Machines: 'Бог Машин',
      Might: 'Бог Силы',
    },
    // Node types for affix display
    nodeTypes: {
      'Micro Talent': 'Малый талант',
      'Medium Talent': 'Средний талант',
      'Legendary Medium Talent': 'Легендарный средний талант',
      'Fixed': 'Фиксированный'
    }
  },
  pactspiritCategories: {
    All: 'Все',
    Attack: 'Атака',
    Erosion: 'Эрозия',
    Spell: 'Заклинание',
    Persistent: 'Устойчивость',
    Summon: 'Призыв',
    Survival: 'Выживание',
    Cold: 'Холод',
    Fire: 'Огонь',
    Lightning: 'Молния'
  },
  vorax: {
    tabName: 'Воракс',
    editGear: 'Редактировать снаряжение Воракс',
    selectLimb: 'Выбрать конечность',
    loadingData: 'Загрузка данных Воракс...',
    baseAffix: 'Базовый аффикс',
    prefixes: 'Префиксы',
    suffixes: 'Суффиксы',
    none: 'Нет',
    selectAffix: 'Выбрать аффикс...',
    toggleLegendary: 'Переключить легендарный режим',
    preview: 'Предпросмотр',
    unnamedItem: 'Безымянный предмет',
    voraxGear: 'Снаряжение Воракс',
    mods: 'Моды',
    noModsSelected: 'Моды не выбраны',
    selectLimbToPreview: 'Выберите конечность для предпросмотра',
    addToInventory: 'Добавить в инвентарь',
    saveChanges: 'Сохранить изменения',
    limbs: {
      chest: 'Нагрудник',
      head: 'Шлем',
      hands: 'Перчатки',
      legs: 'Поножи',
      neck: 'Ожерелье',
      digits: 'Кольцо',
      waist: 'Пояс'
    }
  },
  etherealPrism: {
    installPrismTitle: 'Установить призму - Слот дерева {slot}',
    installEtherealPrismTitle: 'Установить Эфирную Призму - Слот дерева {slot}',
    installInverseImageTitle: 'Установить Обратное Отражение - Слот дерева {slot}',
    etherealPrisms: 'Эфирные Призмы',
    etherealPrism: 'Эфирная Призма',
    inverseImage: 'Обратное Отражение',
    showingType: 'Тип отображения',
    noPrismsCrafted: 'Призмы ещё не созданы',
    craftFirstPrism: 'Создать первую призму',
    craftPrism: 'Создать призму',
    radius: 'Радиус',
    baseAffixLabel: 'Базовый аффикс',
    coreTalentLabel: 'Основной талант',
    equipped: 'Экипировано',
    equippedElsewhere: 'Экипировано в другом месте',
    equip: 'Экипировать',
    edit: 'Редактировать',
    delete: 'Удалить',
    craftPrismTitle: 'Создать призму',
    craftInverseImageTitle: 'Создать Обратное Отражение',
    editPrismTitle: 'Редактировать призму',
    etherealPrismTab: 'Эфирная Призма',
    inverseImageTab: 'Обратное Отражение',
    baseItem: 'Базовый предмет',
    baseItemRequired: 'Базовый предмет *',
    baseItemCannotChange: 'Базовый предмет нельзя изменить при редактировании',
    baseAffix: 'Базовый аффикс',
    baseAffixRequired: 'Базовый аффикс *',
    coreTalent: 'Основной талант',
    coreTalentRequired: 'Основной талант *',
    selectBaseItem: 'Выбрать базовую призму',
    selectBaseAffix: 'Выбрать базовый аффикс',
    noCoreTalent: 'Нет доступного основного таланта',
    coreTalentFixed: 'У этой призмы есть фиксированный основной талант',
    randomAffixes: 'Случайные аффиксы',
    modValues: 'Значения модов',
    inverseImageNotAvailable: 'Данные Обратного Отражения недоступны',
    radiusSlot: 'Слот радиуса',
    rareSlot: 'Редкий слот',
    legendarySlot: 'Легендарный слот',
    radiusSlotDesc: 'Только моды радиуса',
    rareSlotDesc: 'Только редкие моды',
    legendarySlotDesc: 'Только легендарные моды',
    selectRadiusSlot: '-- Выбрать слот радиуса --',
    selectRareSlot: '-- Выбрать редкий слот --',
    selectLegendarySlot: '-- Выбрать легендарный слот --',
    cancel: 'Отмена',
    save: 'Сохранить',
    craft: 'Создать',
    installPrism: 'Установить призму',
    prismInstalledElsewhere: 'Призма установлена в другом месте',
    prismSlotsFull: 'Слоты призм заполнены',
    removePrism: 'Убрать призму',
    cancelPlacement: 'Отмена',
    additionalPointsFromPrism: 'Дополнительные очки от мода призмы',
    prismAddition: 'Бонус призмы',
    // Inverse Image Mod Names
    microTalentEffectRange: 'Диапазон эффекта микро-таланта',
    mediumTalentEffectRange: 'Диапазон эффекта среднего таланта',
    legendaryMediumTalentEffectRange: 'Диапазон эффекта легендарного среднего таланта'
  }
}
