/**
 * Build Planner Taiwanese (Traditional Chinese) translations
 * Machine-assisted translations - Community review needed
 * These translations were generated with AI assistance and may not be
 * accurate for gaming terminology. Native speaker contributions welcome!
 */
import type { BuildPlannerTranslations } from '../types'

export const buildplannerTw: BuildPlannerTranslations = {
  page: {
    backButton: '主頁',
    buildName: '構建名稱：',
    buildNamePlaceholder: '輸入構建名稱'
  },
  hero: {
    sectionTitle: '英雄',
    selectHero: '點擊選擇英雄',
    clickToSelect: '點擊選擇',
    selectHeroToView: '選擇英雄以查看和選擇特性',
    traitLevel: '等級 {level}',
    changeHero: '更換英雄',
    lvl: '等級',
    noTraitsAvailable: '無可用特性',
    selectHeroTitle: '選擇英雄',
    searchHeroes: '搜尋英雄...',
    noHeroesFound: '未找到英雄',
    memoryOf: '{type}之憶',
    clickToManageMemories: '點擊管理記憶',
    clickToEquipMemory: '點擊裝備記憶',
    heroMemories: '英雄記憶',
    noMemoriesCrafted: '尚未製作任何記憶',
    craftFirstMemory: '製作你的第一個記憶',
    noTypeMemories: '沒有可用的{type}記憶',
    craftMemory: '製作記憶',
    memoryNames: {
      Origin: '本源的追憶',
      Discipline: '守己的追憶',
      Progress: '奮進的追憶'
    },
    equipped: '已裝備',
    equip: '裝備',
    delete: '刪除',
    editMemory: '編輯記憶',
    memoryTypeLabel: '記憶類型',
    baseStat: '基礎屬性',
    selectBaseStat: '選擇基礎屬性...',
    fixedAffixes: '固有詞綴',
    randomAffixes: '隨機詞綴',
    fixed: '固有',
    random: '隨機',
    none: '無',
    save: '儲存',
    craft: '製作',
    cancel: '取消',
    cantChangeType: '編輯時無法更改記憶類型',
    loadingMemories: '載入記憶數據中...'
  },
  talentTree: {
    sectionTitle: '天賦樹',
    godTree: '神樹',
    clickToSelect: '點擊選擇',
    classTree: '職業樹',
    selectPreviousFirst: '請先選擇前置天賦',
    treeNumber: '天賦樹 {number}',
    selectPrevious: '選擇前置',
    noTreeSelected: '未選擇天賦樹',
    selectGodTree: '從側邊欄選擇一個神樹以開始構建你的天賦樹',
    selectGodTreeButton: '選擇神樹',
    divinity: '神格',
    slates: '石板',
    totalPoints: '總點數',
    reselectTree: '重新選擇天賦樹',
    reselectConfirmText: '這將重置以下天賦樹及其已分配的點數：',
    confirmContinue: '確定要繼續嗎？',
    reselect: '重新選擇',
    resetPoints: '重置點數',
    resetPointsText: '這將重置所有點數',
    totalPointsReset: '待重置總點數：',
    cancel: '取消',
    reset: '重置',
    selectSlotTitle: '選擇{slot}樹',
    searchTrees: '搜尋天賦樹...',
    loading: '載入中...',
    noTreesSearch: '未找到匹配「{query}」的天賦樹',
    noTreesSlot: '此欄位無可用天賦樹',
    selectNotableTitle: '選擇{threshold}點顯著天賦',
    notableInstruction: '你已在此天賦樹中達到{threshold}點。請選擇以下顯著天賦之一：',
    selected: '已選擇',
    noNotablesAvailable: '此天賦樹在{threshold}點處無可用顯著天賦。'
  },
  skills: {
    sectionTitle: '技能',
    activeSkills: '主動技能',
    passiveSkills: '被動技能',
    energy: '能量',
    maxEnergy: '最大',
    skillsTab: '技能',
    aurasTab: '光環',
    totalEnergy: '總能量：',
    overBudget: '（超出預算！）',
    resetSkills: '重置技能',
    resetSkillsConfirm: '這將重置所有主動技能和光環，包括其輔助寶石。',
    confirmContinue: '確定要繼續嗎？',
    selectActiveSkill: '選擇主動技能',
    selectPassiveSkill: '選擇被動技能',
    searchSkills: '搜尋技能...',
    noSkillsFound: '未找到技能',
    selectSupport: '選擇{type}（欄位 {slot}）',
    searchSupports: '搜尋輔助...',
    noSupportsAvailable: '無可用輔助',
    clearSlot: '清空欄位',
    cancel: '取消',
    reset: '重置',
    removeSkill: '移除技能？',
    removeSkillConfirm: '移除此技能將同時清除分配給它的所有{count}個輔助技能。確定嗎？',
    removeAll: '全部移除',
    clickToSelectActive: '點擊選擇主動技能',
    clickToSelectPassive: '點擊選擇被動技能',
    supportTypes: {
      activation: '激活媒介 / 輔助',
      magnificent: '華麗 / 輔助',
      noble: '高貴 / 輔助',
      support: '輔助',
      activationShort: '激活',
      magnificentShort: '華麗',
      nobleShort: '高貴',
      supportShort: '輔助'
    },
    stats: {
      mainStat: '主屬性',
      manaCost: '魔力消耗',
      castSpeed: '施放速度',
      addedDamage: '額外傷害',
      sealedMana: '封印魔力'
    }
  },
  gear: {
    sectionTitle: '裝備',
    // Inventory
    inventory: '庫存 ({count})',
    addNewItem: '添加新物品',
    noItemsCrafted: '尚未製作任何物品',
    craftFirstItem: '製作您的第一件物品',
    slots: '{filled}/10 槽位',
    // Slot names
    slotsNames: {
      helmet: '頭盔',
      chest: '胸甲',
      gloves: '手套',
      boots: '靴子',
      belt: '腰帶',
      ring1: '戒指 1',
      ring2: '戒指 2',
      necklace: '項鍊',
      mainHand: '武器 1',
      offHand: '武器 2'
    },
    // Crafting modal
    craftGear: '製作裝備',
    editGear: '編輯裝備',
    rarity: {
      Rare: '稀有',
      Legendary: '傳奇'
    },
    rarityCannotChange: '編輯時無法更改稀有度',
    // Form labels
    itemType: '物品類型',
    selectItemType: '選擇物品類型...',
    baseItem: '基礎物品',
    selectBaseItem: '選擇基礎物品...',
    itemLevel: '需求等級 {level}',
    loadingGearData: '加載裝備數據中...',
    beltBlend: '腰帶混合',
    towerSequence: 'TOWER 序列',
    sweetDreamAffix: '甜夢詞綴',
    baseAffix: '基礎詞綴',
    baseAffixPriceless: '無價',
    corrosionImplicit: '腐蝕隱式',
    corrosionDisabled: '(已禁用 - 模組已腐蝕)',
    prefixes: '前綴',
    suffixes: '後綴',
    corroded: '{count}/2 已腐蝕',
    none: '無',
    // Preview
    preview: '預覽',
    selectOptionsToPreview: '選擇選項以預覽物品',
    unnamedItem: '未命名物品',
    addToInventory: '添加到庫存',
    saveChanges: '保存更改',
    // Actions
    equip: '裝備',
    unequip: '卸下',
    edit: '編輯',
    delete: '刪除',
    equipped: '已裝備',
    clickToManage: '點擊管理',
    // Category display names
    categories: {
      helmet: '防具 - 頭盔',
      chest_armor: '防具 - 胸甲',
      gloves: '防具 - 手套',
      boots: '防具 - 靴子',
      shield: '盾牌',
      trinket: '飾品',
      one_handed: '單手武器',
      two_handed: '雙手武器'
    },
    // Sub-type display names
    subTypes: {
      // Helmets
      str_helmet: '力量頭盔',
      dex_helmet: '敏捷頭盔',
      int_helmet: '智力頭盔',
      // Chest
      str_chest_armor: '力量胸甲',
      dex_chest_armor: '敏捷胸甲',
      int_chest_armor: '智力胸甲',
      // Gloves
      str_gloves: '力量手套',
      dex_gloves: '敏捷手套',
      int_gloves: '智力手套',
      // Boots
      str_boots: '力量靴子',
      dex_boots: '敏捷靴子',
      int_boots: '智力靴子',
      // Shields
      str_shield: '力量盾牌',
      dex_shield: '敏捷盾牌',
      int_shield: '智力盾牌',
      // Trinkets
      belt: '腰帶',
      necklace: '項鍊',
      ring: '戒指',
      spirit_ring: '靈戒',
      // 1H Weapons
      cane: '手杖',
      claw: '爪',
      dagger: '匕首',
      'one-handed_axe': '單手斧',
      'one-handed_hammer': '單手錘',
      'one-handed_sword': '單手劍',
      pistol: '手槍',
      rod: '法杖',
      scepter: '權杖',
      wand: '魔杖',
      // 2H Weapons
      bow: '弓',
      crossbow: '弩',
      cudgel: '棍棒',
      fire_cannon: '火炮',
      musket: '火槍',
      tin_staff: '錫杖',
      'two-handed_axe': '雙手斧',
      'two-handed_hammer': '雙手錘',
      'two-handed_sword': '雙手劍'
    },
    // Tooltip labels
    tooltip: {
      prefixes: '前綴',
      suffixes: '後綴',
      tier: 'T'
    }
  },
  pactspirits: {
    sectionTitle: '契靈',
    level: '等級',
    selectPactspirit: '選擇契靈',
    selectPlaceholder: '選擇一個契靈...',
    searchPactspirits: '搜尋契靈...',
    noPactspiritsFound: '未找到匹配條件的契靈。',
    microKismets: '微型命運：',
    mediumKismets: '中型命運：',
    selectKismet: '選擇{type}命運',
    searchKismets: '搜尋命運...',
    loadingKismets: '載入命運中...',
    noKismetsFound: '未找到命運。',
    resetUndetermined: '重置未定命運',
    resetUndeterminedText: '這將卸下未定命運並移除其擴展欄位中安裝的所有命運。',
    confirmContinue: '確定要繼續嗎？',
    cancel: '取消',
    reset: '重置',
    close: '關閉',
    limitReached: '已達上限',
    cannotInstallKismet: '無法安裝命運',
    microLimitReached: '微型命運上限（9）已達！請移除一個現有的微型命運以安裝新的。',
    mediumLimitReached: '中型命運上限（4）已達！請移除一個現有的中型命運以安裝新的。',
    unlockFateSlots: '解鎖命運欄位',
    unlockFateDesc: '選擇如何擴展此未定命運欄位：',
    fateOptionMicro: '{count}個微型命運欄位',
    fateOptionMedium: '{count}個中型命運欄位',
    fateOptionMixed: '{medium}個中型和{micro}個微型命運欄位',
    containsMultipleFates: '包含多種命運。',
    canBeExpanded: '可擴展為多個宿命欄位。',
    installMicroKismet: '安裝小型宿命',
    installMediumKismet: '安裝中型宿命',
    installKismet: '安裝宿命',
    undeterminedFateKismet: '未定命運宿命'
  },
  buildActions: {
    saveBuild: '儲存構建',
    builds: '構建列表',
    newBuild: '+ 新構建',
    noSavedBuilds: '暫無已儲存的構建',
    saveExport: '儲存/導出',
    exportJson: '導出為JSON',
    importJson: '從JSON導入',
    copyShareUrl: '複製分享連結',
    resetBuild: '重置構建',
    resetConfirm: '重置當前構建？所有未儲存的更改將丟失。',
    saveModal: {
      title: '儲存構建',
      warning: '此操作僅將構建儲存到瀏覽器的本地儲存中。如需導出，請使用導出功能。',
      cloudInfo: '此構建將儲存到雲端。當前限制為每個用戶 {limit} 個構建。',
      cloudToggle: '啟用雲端儲存 ({count}/{limit})',
      loginPrompt: '想在雲端儲存您的構建嗎？',
      loginLink: '登入',
      loginPromptEnd: '以使用此功能。',
      buildName: '構建名稱',
      placeholder: '輸入構建名稱...',
      errorNoName: '請輸入構建名稱',
      errorSaveFailed: '儲存構建失敗。儲存空間可能已滿。',
      errorCloudLimit: '已達到雲端構建限制 ({limit})。刪除雲端構建以儲存更多。',
      errorCloudSaveFailed: '儲存到雲端失敗。請重試。',
      cancel: '取消',
      save: '儲存'
    },
    deleteModal: {
      title: '刪除構建',
      warning: '確定要刪除「{name}」嗎？',
      irreversible: '此操作無法復原。',
      cancel: '取消',
      confirm: '刪除'
    }
  },
  toasts: {
    buildSaved: '構建儲存成功',
    saveSuccessCloud: '構建"{name}"已儲存到雲端！',
    newBuildCreated: '新構建已建立',
    buildLoaded: '構建已載入',
    buildDeleted: '構建已刪除',
    deleteSuccessCloud: '雲端構建"{name}"已刪除',
    deleteFailedCloud: '刪除雲端構建失敗',
    loadFailed: '加載構建失敗',
    buildReset: '構建已重置',
    importSuccess: '構建導入成功！',
    exportSuccess: '構建已導出',
    shareUrlCopied: '分享連結已複製到剪貼簿'
  },
  importModal: {
    title: '導入構建',
    pasteJson: '貼上JSON',
    uploadFile: '上傳檔案',
    dragDrop: '將.json檔案拖放到此處',
    clickToSelect: '點擊選擇',
    selected: '已選擇：',
    cancel: '取消',
    import: '導入',
    pastePlaceholder: '在此貼上構建JSON...',
    errorNoCode: '請貼上構建JSON',
    errorNoFile: '請先選擇檔案',
    errorInvalidJson: '無效的構建JSON',
    errorWrongFileType: '請選擇.json檔案',
    errorReadFailed: '檔案讀取失敗'
  },
  settings: {
    title: '設定',
    language: '語言',
    done: '完成',
    comingSoon: '即將推出',
    close: '關閉設定'
  },
  divinity: {
    // Grid controls
    save: '儲存',
    edit: '編輯',
    inventory: '倉庫',
    reselect: '重選',
    reset: '重置',
    // Context menu
    rotateCw: '順時針旋轉',
    rotateCcw: '逆時針旋轉',
    flipHorizontal: '水平翻轉',
    flipVertical: '垂直翻轉',
    editSlate: '編輯石板',
    removeSlate: '移除石板',
    // Inventory drawer
    inventoryTitle: '石板倉庫',
    noSlatesCrafted: '尙未製作石板',
    craftFirstSlate: '製作第一塊石板',
    craftSlate: '製作石板',
    // Slate card
    placed: '已放置',
    affixes: '詞綴',
    affix: '詞綴',
    rareSlate: '稀有石板',
    legendarySlate: '傳奇石板',
    deleteSlate: '刪除此石板？',
    cancel: '取消',
    delete: '刪除',
    unequip: '卸下',
    // Crafting modal
    craftSlateTitle: '製作石板',
    editSlateTitle: '編輯石板',
    craftLegendarySlateTitle: '製作傳奇石板',
    editLegendarySlateTitle: '編輯傳奇石板',
    god: '神',
    shapeAndOrientation: '形狀與方向',
    rotate: '旋轉',
    flipH: '水平翻轉',
    flipV: '垂直翻轉',
    affixesLabel: '詞綴',
    slot: '插槽',
    legendaryTemplate: '傳奇模板',
    fixedAffix: '固定詞綴',
    saveChanges: '儲存更改',
    saveToInventory: '儲存至倉庫',
    cancelCrafting: '取消',
    // Node tooltip
    leftClickToAdd: '左鍵：添加點數',
    rightClickToRemove: '右鍵：移除點數',
    notableTalent: '顯著天賦',
    points: '點數',
    noValidPlacement: '未找到有效放置位置。請重新排列石板以騰出空間。',
    // Affix select
    selectAffix: '選擇詞綴...',
    searchAffix: '輸入搜索...',
    noAffixMatches: '無匹配結果',
    // God names
    godNames: {
      Hunting: '狩獵女神',
      Deception: '欺詐女神',
      Knowledge: '知識女神',
      War: '戰爭之神',
      Machines: '機械之神',
      Might: '力量之神',
    },
    // Node types for affix display
    nodeTypes: {
      'Micro Talent': '小型天賦',
      'Medium Talent': '中型天賦',
      'Legendary Medium Talent': '傳奇中型天賦',
      'Fixed': '固定'
    }
  },
  pactspiritCategories: {
    All: '全部',
    Attack: '攻擊',
    Erosion: '侵蝕',
    Spell: '法術',
    Persistent: '持續',
    Summon: '召喚',
    Survival: '生存',
    Cold: '寒冷',
    Fire: '火焰',
    Lightning: '閃電'
  },
  vorax: {
    tabName: '沃拉斯',
    editGear: '編輯沃拉斯裝備',
    selectLimb: '選擇部位',
    loadingData: '載入沃拉斯數據中...',
    baseAffix: '基礎詞綴',
    prefixes: '前綴',
    suffixes: '後綴',
    none: '無',
    selectAffix: '選擇詞綴...',
    toggleLegendary: '切換傳奇模式',
    preview: '預覽',
    unnamedItem: '未命名物品',
    voraxGear: '沃拉斯裝備',
    mods: '模組',
    noModsSelected: '未選擇模組',
    selectLimbToPreview: '選擇部位以預覽',
    addToInventory: '添加到庫存',
    saveChanges: '保存更改',
    limbs: {
      chest: '胸甲',
      head: '頭盔',
      hands: '手套',
      legs: '腿甲',
      neck: '項鍊',
      digits: '指環',
      waist: '腰帶'
    }
  },
  etherealPrism: {
    installPrismTitle: '安裝稜鏡 - 天賦樹槽位 {slot}',
    installEtherealPrismTitle: '安裝幽影稜鏡 - 天賦樹槽位 {slot}',
    installInverseImageTitle: '安裝反射之影 - 天賦樹槽位 {slot}',
    etherealPrisms: '異度稜鏡',
    etherealPrism: '幽影稜鏡',
    inverseImage: '反射之影',
    showingType: '顯示類型',
    noPrismsCrafted: '尚未製作稜鏡',
    craftFirstPrism: '製作第一個稜鏡',
    craftPrism: '製作稜鏡',
    radius: '範圍',
    baseAffixLabel: '基礎詞綴',
    coreTalentLabel: '核心天賦',
    equipped: '已裝備',
    equippedElsewhere: '已在其他位置裝備',
    equip: '裝備',
    edit: '編輯',
    delete: '刪除',
    craftPrismTitle: '製作稜鏡',
    craftInverseImageTitle: '製作反射之影',
    editPrismTitle: '編輯稜鏡',
    etherealPrismTab: '幽影稜鏡',
    inverseImageTab: '反射之影',
    baseItem: '基礎物品',
    baseItemRequired: '基礎物品 *',
    baseItemCannotChange: '編輯時無法更改基礎物品',
    baseAffix: '基礎詞綴',
    baseAffixRequired: '基礎詞綴 *',
    coreTalent: '核心天賦',
    coreTalentRequired: '核心天賦 *',
    selectBaseItem: '選擇基礎稜鏡',
    selectBaseAffix: '選擇基礎詞綴',
    noCoreTalent: '無核心天賦可用',
    coreTalentFixed: '此稜鏡擁有固定的核心天賦',
    randomAffixes: '隨機詞綴',
    modValues: '詞綴數值',
    inverseImageNotAvailable: '反射之影資料不可用',
    radiusSlot: '範圍槽',
    rareSlot: '稀有槽',
    legendarySlot: '傳奇槽',
    radiusSlotDesc: '僅限範圍模組',
    rareSlotDesc: '僅限稀有模組',
    legendarySlotDesc: '僅限傳奇模組',
    selectRadiusSlot: '-- 選擇範圍槽 --',
    selectRareSlot: '-- 選擇稀有槽 --',
    selectLegendarySlot: '-- 選擇傳奇槽 --',
    cancel: '取消',
    save: '保存',
    craft: '製作',
    installPrism: '安裝稜鏡',
    prismInstalledElsewhere: '稜鏡已在其他位置安裝',
    prismSlotsFull: '稜鏡槽位已滿',
    removePrism: '移除稜鏡',
    cancelPlacement: '取消',
    additionalPointsFromPrism: '稜鏡模組額外點數',
    prismAddition: '稜鏡加成',
    // Inverse Image Mod Names
    microTalentEffectRange: '微型天賦效果範圍',
    mediumTalentEffectRange: '中型天賦效果範圍',
    legendaryMediumTalentEffectRange: '傳奇中型天賦效果範圍'
  }
}
