import type { UITranslations } from '../types'

export const uiCn: UITranslations = {
  settings: {
    title: '设置',
    account: {
      tab: '账户',
      title: '账户设置',
      displayName: '显示名称',
      displayNameDescription: '这是将在整个网站上显示的名称。留空以使用您的用户名。',
      displayNamePlaceholder: '输入显示名称',
      displayNameSuccess: '显示名称更新成功！',
      saving: '保存中...',
      saveDisplayName: '保存显示名称',
      dangerZone: '危险区域',
      deleteAccountWarning: '一旦删除您的账户，将无法恢复。此操作无法撤销。您所有保存的构建和数据将被永久删除。',
      deleteAccount: '删除账户',
      deleteConfirmText: '您确定要删除您的账户吗？这是<span class="text-red-400 font-semibold">不可逆转的</span>！',
      deleteConfirmInstruction: '请在下方文本框中输入"<span class="text-white font-medium">我确定</span>"以继续。',
      deleteConfirmPlaceholder: "输入'我确定'以确认",
      cancel: '取消',
      deleting: '删除中...',
      confirmDelete: '确认删除',
    },
  },
  nav: {
    home: '首页',
    gameMechanics: '游戏机制',
    seasonMechanics: '赛季机制',
    tools: '工具',
    buildPlanner: 'Build模拟器',
    voidchartPlanner: '虚空星图规划器',
    about: '关于',
    impressum: '法律声明',
  },
  mobileNav: {
    menu: '菜单',
    closeMenu: '关闭菜单',
    language: '语言',
  },
  footer: {
    copyright: '© {year} TLI 宝典。保留所有权利。',
  },
  home: {
    latest: '最新',
    filterAll: '全部',
    filterGuides: '攻略',
    filterTools: '工具',
    filterUpdates: '更新',
  },
  menuCategories: {
    combatMechanics: '战斗机制',
    gameSystems: '游戏系统',
    seasons1to4: '赛季 1-4',
    seasons5to8: '赛季 5-8',
    seasons9to11: '赛季 9-11',
    seasons13: '赛季 13',
  },
  menuItems: {
    // Combat Mechanics
    defences: '防御',
    defencesDesc: '护甲、抗性和伤害减免',
    ailments: '异常状态',
    ailmentsDesc: '状态效果和持续伤害',
    melee: '近战',
    meleeDesc: ' steep Strike、多击和连击',
    spells: '法术',
    spellsDesc: '法术爆发、缠绕和连击',
    minions: '召唤物',
    minionsDesc: '召唤物及其运作方式',
    damageOverTime: '持续伤害',
    damageOverTimeDesc: '关于持续伤害的一切',
    buffsAndDebuffs: '增益与减益',
    buffsAndDebuffsDesc: '祝福、弱化等',
    auras: '光环',
    aurasDesc: '关于光环和封印法力的一切',
    curses: '诅咒',
    cursesDesc: '关于诅咒的一切',
    // Game Systems
    crafting: '打造',
    craftingDesc: '打造系统和机制',
    // Seasons
    darkSurge: '黑暗 surge',
    darkSurgeDesc: '黑暗 surge 赛季机制',
    blacksail: '黑帆',
    blacksailDesc: '黑帆赛季机制',
    cube: '魔方',
    cubeDesc: '魔方赛季机制',
    aterna: 'Aterna',
    aternaDesc: 'Aterna 赛季机制',
    nightmare: '噩梦',
    nightmareDesc: '噩梦赛季机制',
    whisperingMist: '低语之雾',
    whisperingMistDesc: '低语之雾赛季机制',
    clockworkBallet: '发条芭蕾',
    clockworkBalletDesc: '发条芭蕾赛季机制',
    theFrozenCanvas: '冰封画布',
    theFrozenCanvasDesc: '冰封画布赛季机制',
    arcana: '奥秘',
    arcanaDesc: '奥秘赛季机制',
    sandlord: '沙领主',
    sandlordDesc: '沙领主赛季机制',
    outlaw: ' outlaw',
    outlawDesc: ' outlaw 赛季机制',
    overrealm: 'Overrealm',
    overrealmDesc: 'Overrealm 赛季机制',
    vorax: 'Vorax',
    voraxDesc: 'Vorax 赛季机制',
  },
  support: {
    message: '支持我们 ❤️.',
  },
  auth: {
    login: '登录',
    logout: '退出',
    register: '注册',
    username: '用户名',
    email: '电子邮箱',
    displayName: '显示名称',
    password: '密码',
    confirmPassword: '确认密码',
    loginButton: '登录',
    registerButton: '注册',
    alreadyHaveAccount: '已有账户？',
    dontHaveAccount: '没有账户？',
    loginSuccess: '登录成功！',
    registerSuccess: '注册成功！您已自动登录。',
    logoutSuccess: '退出成功',
    loginError: '登录失败',
    registerError: '注册失败',
    validation: {
      usernameRequired: '请输入用户名',
      usernameMinLength: '用户名至少需要3个字符',
      usernameMaxLength: '用户名不能超过50个字符',
      emailRequired: '请输入电子邮箱',
      emailInvalid: '请输入有效的电子邮箱地址',
      passwordRequired: '请输入密码',
      passwordMinLength: '密码至少需要6个字符',
      passwordMaxLength: '密码不能超过100个字符',
      passwordsDoNotMatch: '两次输入的密码不一致',
      displayNameMaxLength: '显示名称不能超过100个字符',
      passwordRequirements: {
        title: '密码必须包含:',
        minLength: '至少6个字符',
        uppercase: '大写字母 (A-Z)',
        lowercase: '小写字母 (a-z)',
        digit: '数字 (0-9)',
        special: '特殊字符 (!@#$%^&* 等)',
      },
    },
  },
}
