import type { UITranslations } from '../types'

export const uiEn: UITranslations = {
  settings: {
    title: 'Settings',
    account: {
      tab: 'Account',
      title: 'Account Settings',
      displayName: 'Display Name',
      displayNameDescription: 'This is the name that will be displayed across the site. Leave empty to use your username.',
      displayNamePlaceholder: 'Enter display name',
      displayNameSuccess: 'Display name updated successfully!',
      saving: 'Saving...',
      saveDisplayName: 'Save Display Name',
      dangerZone: 'DANGER ZONE',
      deleteAccountWarning: 'Once you delete your account, there is no going back. This action cannot be undone. All your saved builds and data will be permanently removed.',
      deleteAccount: 'Delete Account',
      deleteConfirmText: 'Are you sure you want to delete your Account? This is <span class="text-red-400 font-semibold">irreversible</span>!',
      deleteConfirmInstruction: 'To continue write "<span class="text-white font-medium">I am sure</span>" into the text field below.',
      deleteConfirmPlaceholder: "Type 'I am sure' to confirm",
      cancel: 'Cancel',
      deleting: 'Deleting...',
      confirmDelete: 'Confirm Delete',
    },
  },
  nav: {
    home: 'Home',
    gameMechanics: 'Game Mechanics',
    seasonMechanics: 'Season Mechanics',
    tools: 'Tools',
    buildPlanner: 'Build Planner',
    voidchartPlanner: 'VoidChart Planner',
    about: 'About',
    impressum: 'Impressum',
  },
  mobileNav: {
    menu: 'Menu',
    closeMenu: 'Close menu',
    language: 'Language',
  },
  footer: {
    copyright: '© {year} TLI Compendium. All rights reserved.',
  },
  home: {
    latest: 'LATEST',
    filterAll: 'All',
    filterGuides: 'Guides',
    filterTools: 'Tools',
    filterUpdates: 'Updates',
  },
  menuCategories: {
    combatMechanics: 'COMBAT MECHANICS',
    gameSystems: 'GAME SYSTEMS',
    seasons1to4: 'SEASONS 1-4',
    seasons5to8: 'SEASONS 5-8',
    seasons9to11: 'SEASONS 9-11',
    seasons13: 'SEASONS 13',
  },
  menuItems: {
    // Combat Mechanics
    defences: 'Defences',
    defencesDesc: 'Armor, resistance, and mitigation',
    ailments: 'Ailments',
    ailmentsDesc: 'Status effects and damage over time',
    melee: 'Melee',
    meleeDesc: 'Steep Strike, Multistrike, and Combo',
    spells: 'Spells',
    spellsDesc: 'Spellburst, Tangle, and Combo',
    minions: 'Minions',
    minionsDesc: 'Minions & how they work',
    damageOverTime: 'Damage over Time',
    damageOverTimeDesc: 'Everything about DoT\'s',
    buffsAndDebuffs: 'Buffs & Debuffs',
    buffsAndDebuffsDesc: 'Blessings, Weaken & more',
    auras: 'Auras',
    aurasDesc: 'Everything about Auras & Sealed Mana',
    curses: 'Curses',
    cursesDesc: 'Everything about curses',
    // Game Systems
    crafting: 'Crafting',
    craftingDesc: 'Crafting systems and mechanics',
    // Seasons
    darkSurge: 'Dark Surge',
    darkSurgeDesc: 'Dark Surge season mechanics',
    blacksail: 'Blacksail',
    blacksailDesc: 'Blacksail season mechanics',
    cube: 'Cube',
    cubeDesc: 'Cube season mechanics',
    aterna: 'Aterna',
    aternaDesc: 'Aterna season mechanics',
    nightmare: 'Nightmare',
    nightmareDesc: 'Nightmare season mechanics',
    whisperingMist: 'Whispering Mist',
    whisperingMistDesc: 'Whispering Mist season mechanics',
    clockworkBallet: 'Clockwork Ballet',
    clockworkBalletDesc: 'Clockwork Ballet season mechanics',
    theFrozenCanvas: 'The Frozen Canvas',
    theFrozenCanvasDesc: 'The Frozen Canvas season mechanics',
    arcana: 'Arcana',
    arcanaDesc: 'Arcana season mechanics',
    sandlord: 'Sandlord',
    sandlordDesc: 'Sandlord season mechanics',
    outlaw: 'Outlaw',
    outlawDesc: 'Outlaw season mechanics',
    overrealm: 'Overrealm',
    overrealmDesc: 'Overrealm season mechanics',
    vorax: 'Vorax',
    voraxDesc: 'Vorax season mechanics',
  },
  support: {
    message: 'Show your support ❤️.',
  },
  auth: {
    login: 'Login',
    logout: 'Logout',
    register: 'Register',
    username: 'Username',
    email: 'Email',
    displayName: 'Display Name',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    loginButton: 'Login',
    registerButton: 'Register',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    loginSuccess: 'Login successful!',
    registerSuccess: 'Registration successful! You have been logged in automatically.',
    logoutSuccess: 'Logged out successfully',
    loginError: 'Login failed',
    registerError: 'Registration failed',
    validation: {
      usernameRequired: 'Username is required',
      usernameMinLength: 'Username must be at least 3 characters',
      usernameMaxLength: 'Username must be less than 50 characters',
      emailRequired: 'Email is required',
      emailInvalid: 'Please enter a valid email address',
      passwordRequired: 'Password is required',
      passwordMinLength: 'Password must be at least 6 characters',
      passwordMaxLength: 'Password must be less than 100 characters',
      passwordsDoNotMatch: 'Passwords do not match',
      displayNameMaxLength: 'Display name must be less than 100 characters',
      passwordRequirements: {
        title: 'Password must contain:',
        minLength: 'At least 6 characters',
        uppercase: 'Uppercase letter (A-Z)',
        lowercase: 'Lowercase letter (a-z)',
        digit: 'Number (0-9)',
        special: 'Special character (!@#$%^&* etc.)',
      },
    },
  },
}
