import type { UITranslations } from '../types'

export const uiJa: UITranslations = {
  settings: {
    title: '設定',
    account: {
      tab: 'アカウント',
      title: 'アカウント設定',
      displayName: '表示名',
      displayNameDescription: 'これはサイト全体に表示される名前です。空白のままにすると、ユーザー名が使用されます。',
      displayNamePlaceholder: '表示名を入力',
      displayNameSuccess: '表示名が正常に更新されました！',
      saving: '保存中...',
      saveDisplayName: '表示名を保存',
      dangerZone: '危険区域',
      deleteAccountWarning: 'アカウントを削除すると、元に戻すことはできません。この操作は取り消しできません。保存されたすべてのビルドとデータが永久に削除されます。',
      deleteAccount: 'アカウントを削除',
      deleteConfirmText: 'アカウントを削除してもよろしいですか？これは<span class="text-red-400 font-semibold">元に戻せません</span>！',
      deleteConfirmInstruction: '続行するには、下のテキストフィールドに「<span class="text-white font-medium">I am sure</span>」と入力してください。',
      deleteConfirmPlaceholder: "'I am sure'と入力して確認",
      cancel: 'キャンセル',
      deleting: '削除中...',
      confirmDelete: '削除を確認',
    },
  },
  nav: {
    home: 'ホーム',
    gameMechanics: 'ゲームシステム',
    seasonMechanics: 'シーズンシステム',
    tools: 'ツール',
    buildPlanner: 'ビルドプランナー',
    voidchartPlanner: 'ボイドチャートプランナー',
    about: '概要',
    impressum: '法的通知',
  },
  mobileNav: {
    menu: 'メニュー',
    closeMenu: 'メニューを閉じる',
    language: '言語',
  },
  footer: {
    copyright: '© {year} TLI Compendium. All rights reserved.',
  },
  home: {
    latest: '最新',
    filterAll: 'すべて',
    filterGuides: 'ガイド',
    filterTools: 'ツール',
    filterUpdates: '更新',
  },
  menuCategories: {
    combatMechanics: '戦闘システム',
    gameSystems: 'ゲームシステム',
    seasons1to4: 'シーズン 1-4',
    seasons5to8: 'シーズン 5-8',
    seasons9to11: 'シーズン 9-11',
    seasons13: 'シーズン 13',
  },
  menuItems: {
    // Combat Mechanics
    defences: '防御',
    defencesDesc: 'アーマー、耐性、軽減',
    ailments: '状態異常',
    ailmentsDesc: '状態効果と継続ダメージ',
    melee: '近接',
    meleeDesc: 'Steep Strike、Multistrike、Combo',
    spells: 'スペル',
    spellsDesc: 'Spellburst、Tangle、Combo',
    minions: 'ミニオン',
    minionsDesc: 'ミニオンとその仕組み',
    damageOverTime: '継続ダメージ',
    damageOverTimeDesc: 'DoTについて全て',
    buffsAndDebuffs: 'バフとデバフ',
    buffsAndDebuffsDesc: '祝福、弱体化など',
    auras: 'オーラ',
    aurasDesc: 'オーラとシールドマナについて全て',
    curses: '呪い',
    cursesDesc: '呪いについて全て',
    // Game Systems
    crafting: 'クラフト',
    craftingDesc: 'クラフトシステムと仕組み',
    // Seasons
    darkSurge: 'ダークサージ',
    darkSurgeDesc: 'ダークサージシーズンシステム',
    blacksail: 'ブラックセイル',
    blacksailDesc: 'ブラックセイルシーズンシステム',
    cube: 'キューブ',
    cubeDesc: 'キューブシーズンシステム',
    aterna: 'アテルナ',
    aternaDesc: 'アテルナシーズンシステム',
    nightmare: 'ナイトメア',
    nightmareDesc: 'ナイトメアシーズンシステム',
    whisperingMist: 'ウィスパリングミスト',
    whisperingMistDesc: 'ウィスパリングミストシーズンシステム',
    clockworkBallet: 'クロックワークバレエ',
    clockworkBalletDesc: 'クロックワークバレエシーズンシステム',
    theFrozenCanvas: 'フローズンキャンバス',
    theFrozenCanvasDesc: 'フローズンキャンバスシーズンシステム',
    arcana: 'アルカナ',
    arcanaDesc: 'アルカナシーズンシステム',
    sandlord: 'サンドロード',
    sandlordDesc: 'サンドロードシーズンシステム',
    outlaw: 'アウトロー',
    outlawDesc: 'アウトローシーズンシステム',
    overrealm: 'オーバーレルム',
    overrealmDesc: 'オーバーレルムシーズンシステム',
    vorax: 'ボラックス',
    voraxDesc: 'ボラックスシーズンシステム',
  },
  support: {
    message: '応援してください ❤️.',
  },
  auth: {
    login: 'ログイン',
    logout: 'ログアウト',
    register: '登録',
    username: 'ユーザー名',
    email: 'メールアドレス',
    displayName: '表示名',
    password: 'パスワード',
    confirmPassword: 'パスワード（確認）',
    loginButton: 'ログイン',
    registerButton: '登録',
    alreadyHaveAccount: 'すでにアカウントをお持ちですか？',
    dontHaveAccount: 'アカウントをお持ちでないですか？',
    loginSuccess: 'ログイン成功！',
    registerSuccess: '登録成功！自動的にログインしました。',
    logoutSuccess: 'ログアウト成功',
    loginError: 'ログイン失敗',
    registerError: '登録失敗',
    validation: {
      usernameRequired: 'ユーザー名を入力してください',
      usernameMinLength: 'ユーザー名は3文字以上である必要があります',
      usernameMaxLength: 'ユーザー名は50文字以下である必要があります',
      emailRequired: 'メールアドレスを入力してください',
      emailInvalid: '有効なメールアドレスを入力してください',
      passwordRequired: 'パスワードを入力してください',
      passwordMinLength: 'パスワードは6文字以上である必要があります',
      passwordMaxLength: 'パスワードは100文字以下である必要があります',
      passwordsDoNotMatch: 'パスワードが一致しません',
      displayNameMaxLength: '表示名は100文字以下である必要があります',
      passwordRequirements: {
        title: 'パスワードには以下が必要です:',
        minLength: '6文字以上',
        uppercase: '大文字 (A-Z)',
        lowercase: '小文字 (a-z)',
        digit: '数字 (0-9)',
        special: '特殊文字 (!@#$%^&* など)',
      },
    },
  },
}
