/*
 * 26-2-19 검수됨. Pyo
 */
import type { UITranslations } from '../types'

export const uiKo: UITranslations = {
    settings: {
    title: '설정',
    account: {
      tab: '계정',
      title: '계정 설정',
      displayName: '표시 이름',
      displayNameDescription: '사이트 전체에 표시될 이름입니다. 비워두면 사용자 이름이 사용됩니다.',
      displayNamePlaceholder: '표시 이름 입력',
      displayNameSuccess: '표시 이름이 성공적으로 업데이트되었습니다!',
      saving: '저장 중...',
      saveDisplayName: '표시 이름 저장',
      dangerZone: '위험 구역',
      deleteAccountWarning: '계정을 삭제하면 되돌릴 수 없습니다. 이 작업은 취소할 수 없습니다. 저장된 모든 빌드와 데이터가 영구적으로 삭제됩니다.',
      deleteAccount: '계정 삭제',
      deleteConfirmText: '계정을 삭제하시겠습니까? 이 작업은<span class="text-red-400 font-semibold">되돌릴 수 없습니다</span>!',
      deleteConfirmInstruction: '계속하려면 아래 텍스트 필드에 "<span class="text-white font-medium">I am sure</span>"를 입력하세요.',
      deleteConfirmPlaceholder: "'I am sure'를 입력하여 확인",
      cancel: '취소',
      deleting: '삭제 중...',
      confirmDelete: '삭제 확인',
    },
  },
  nav: {
    home: '홈',
    gameMechanics: '게임 메커니즘',
    seasonMechanics: '시즌 메커니즘',
    tools: '도구',
    buildPlanner: '빌드 플래너',
    voidchartPlanner: '허공의 성도 플래너',
    about: '소개',
    impressum: '법적 고지',
  },
  mobileNav: {
    menu: '메뉴',
    closeMenu: '메뉴 닫기',
    language: '언어',
  },
  footer: {
    copyright: '© {year} TLI Compendium. All rights reserved.',
  },
  home: {
    latest: '최신',
    filterAll: '전체',
    filterGuides: '가이드',
    filterTools: '도구',
    filterUpdates: '업데이트',
  },
  menuCategories: {
    combatMechanics: '전투 메커니즘',
    gameSystems: '게임 시스템',
    seasons1to4: '시즌 1-4',
    seasons5to8: '시즌 5-8',
    seasons9to11: '시즌 9-11',
    seasons13: '시즌 13',
  },
  menuItems: {
    // Combat Mechanics
    defences: '방어',
    defencesDesc: '방어구, 저항 및 피해 감소',
    ailments: '상태 이상',
    ailmentsDesc: '상태 효과 및 지속 피해',
    melee: '근접',
    meleeDesc: '슬래시, 연속 공격 및 콤보',
    spells: '주문',
    spellsDesc: '매직 버스트, 부착 및 콤보',
    minions: '소환체',
    minionsDesc: '소환체 및 작동 방식',
    damageOverTime: '지속 피해',
    damageOverTimeDesc: '지속 피해에 관한 모든 것',
    buffsAndDebuffs: '버프 및 디버프',
    buffsAndDebuffsDesc: '축복, 약화 등',
    auras: '오라',
    aurasDesc: '오라 및 봉인에 관한 모든 것',
    curses: '저주',
    cursesDesc: '저주에 관한 모든 것',
    // Game Systems
    crafting: '제작',
    craftingDesc: '제작 시스템 및 메커니즘',
    // Seasons
    darkSurge: '검은 물결',
    darkSurgeDesc: '검은 물결 시즌 메커니즘',
    blacksail: '검은 돛',
    blacksailDesc: '검은 돛 시즌 메커니즘',
    cube: '큐브',
    cubeDesc: '큐브 시즌 메커니즘',
    aterna: '영원한 미궁',
    aternaDesc: '영원한 미궁 시즌 메커니즘',
    nightmare: '악몽',
    nightmareDesc: '악몽 시즌 메커니즘',
    whisperingMist: '괴담',
    whisperingMistDesc: '괴담 시즌 메커니즘',
    clockworkBallet: '기계인형 클럽',
    clockworkBalletDesc: '기계인형 클럽 시즌 메커니즘',
    theFrozenCanvas: '설원',
    theFrozenCanvasDesc: '설원 시즌 메커니즘',
    arcana: '타로',
    arcanaDesc: '타로 시즌 메커니즘',
    sandlord: '사막의 군주',
    sandlordDesc: '사막의 군주 시즌 메커니즘',
    outlaw: '현상 수배',
    outlawDesc: '현상 수배 시즌 메커니즘',
    overrealm: '이계',
    overrealmDesc: '이계 시즌 메커니즘',
    vorax: '블러드 러스트',
    voraxDesc: '블러드 러스트 시즌 메커니즘',
  },
  support: {
    message: '응원해주세요 ❤️.',
  },
  auth: {
    login: '로그인',
    logout: '로그아웃',
    register: '회원가입',
    username: '사용자 이름',
    email: '이메일',
    displayName: '표시 이름',
    password: '비밀번호',
    confirmPassword: '비밀번호 확인',
    loginButton: '로그인',
    registerButton: '회원가입',
    alreadyHaveAccount: '이미 계정이 있으신가요?',
    dontHaveAccount: '계정이 없으신가요?',
    loginSuccess: '로그인 성공!',
    registerSuccess: '회원가입 성공! 자동으로 로그인되었습니다.',
    logoutSuccess: '로그아웃 성공',
    loginError: '로그인 실패',
    registerError: '회원가입 실패',
    validation: {
      usernameRequired: '사용자 이름을 입력해주세요',
      usernameMinLength: '사용자 이름은 최소 3자 이상이어야 합니다',
      usernameMaxLength: '사용자 이름은 50자 이하여야 합니다',
      emailRequired: '이메일을 입력해주세요',
      emailInvalid: '유효한 이메일 주소를 입력해주세요',
      passwordRequired: '비밀번호를 입력해주세요',
      passwordMinLength: '비밀번호는 최소 6자 이상이어야 합니다',
      passwordMaxLength: '비밀번호는 100자 이하여야 합니다',
      passwordsDoNotMatch: '비밀번호가 일치하지 않습니다',
      displayNameMaxLength: '표시 이름은 100자 이하여야 합니다',
      passwordRequirements: {
        title: '비밀번호는 다음을 포함해야 합니다:',
        minLength: '최소 6자',
        uppercase: '대문자 (A-Z)',
        lowercase: '소문자 (a-z)',
        digit: '숫자 (0-9)',
        special: '특수문자 (!@#$%^&* 등)',
      },
    },
  },
}
