/*
 * 26-2-19 검수됨. Pyo
 */
import type { UITranslations } from '../types'

export const uiKo: UITranslations = {
  nav: {
    home: '홈',
    gameMechanics: '게임 메커니즘',
    seasonMechanics: '시즌 메커니즘',
    tools: '도구',
    buildPlanner: '빌드 플래너',
    voidchartPlanner: '허공의 성도 플래너',
    about: '소개',
    impressum: '법적 고지',
  },
  mobileNav: {
    menu: '메뉴',
    closeMenu: '메뉴 닫기',
    language: '언어',
  },
  footer: {
    copyright: '© {year} TLI Compendium. All rights reserved.',
  },
  home: {
    latest: '최신',
    filterAll: '전체',
    filterGuides: '가이드',
    filterTools: '도구',
    filterUpdates: '업데이트',
  },
  menuCategories: {
    combatMechanics: '전투 메커니즘',
    gameSystems: '게임 시스템',
    seasons1to4: '시즌 1-4',
    seasons5to8: '시즌 5-8',
    seasons9to11: '시즌 9-11',
    seasons13: '시즌 13',
  },
  menuItems: {
    // Combat Mechanics
    defences: '방어',
    defencesDesc: '방어구, 저항 및 피해 감소',
    ailments: '상태 이상',
    ailmentsDesc: '상태 효과 및 지속 피해',
    melee: '근접',
    meleeDesc: '슬래시, 연속 공격 및 콤보',
    spells: '주문',
    spellsDesc: '매직 버스트, 부착 및 콤보',
    minions: '소환체',
    minionsDesc: '소환체 및 작동 방식',
    damageOverTime: '지속 피해',
    damageOverTimeDesc: '지속 피해에 관한 모든 것',
    buffsAndDebuffs: '버프 및 디버프',
    buffsAndDebuffsDesc: '축복, 약화 등',
    auras: '오라',
    aurasDesc: '오라 및 봉인에 관한 모든 것',
    curses: '저주',
    cursesDesc: '저주에 관한 모든 것',
    // Game Systems
    crafting: '제작',
    craftingDesc: '제작 시스템 및 메커니즘',
    // Seasons
    darkSurge: '검은 물결',
    darkSurgeDesc: '검은 물결 시즌 메커니즘',
    blacksail: '검은 돛',
    blacksailDesc: '검은 돛 시즌 메커니즘',
    cube: '큐브',
    cubeDesc: '큐브 시즌 메커니즘',
    aterna: '영원한 미궁',
    aternaDesc: '영원한 미궁 시즌 메커니즘',
    nightmare: '악몽',
    nightmareDesc: '악몽 시즌 메커니즘',
    whisperingMist: '괴담',
    whisperingMistDesc: '괴담 시즌 메커니즘',
    clockworkBallet: '기계인형 클럽',
    clockworkBalletDesc: '기계인형 클럽 시즌 메커니즘',
    theFrozenCanvas: '설원',
    theFrozenCanvasDesc: '설원 시즌 메커니즘',
    arcana: '타로',
    arcanaDesc: '타로 시즌 메커니즘',
    sandlord: '사막의 군주',
    sandlordDesc: '사막의 군주 시즌 메커니즘',
    outlaw: '현상 수배',
    outlawDesc: '현상 수배 시즌 메커니즘',
    overrealm: '이계',
    overrealmDesc: '이계 시즌 메커니즘',
    vorax: '블러드 러스트',
    voraxDesc: '블러드 러스트 시즌 메커니즘',
  },
  support: {
    message: '응원해주세요 ❤️.',
  },
}
