import type { UITranslations } from '../types'

export const uiRu: UITranslations = {
  settings: {
    title: 'Настройки',
    account: {
      tab: 'Аккаунт',
      title: 'Настройки аккаунта',
      displayName: 'Отображаемое имя',
      displayNameDescription: 'Это имя будет отображаться на сайте. Оставьте пустым, чтобы использовать имя пользователя.',
      displayNamePlaceholder: 'Введите отображаемое имя',
      displayNameSuccess: 'Отображаемое имя успешно обновлено!',
      saving: 'Сохранение...',
      saveDisplayName: 'Сохранить отображаемое имя',
      dangerZone: 'ОПАСНАЯ ЗОНА',
      deleteAccountWarning: 'После удаления аккаунта пути назад нет. Это действие нельзя отменить. Все ваши сохраненные сборки и данные будут безвозвратно удалены.',
      deleteAccount: 'Удалить аккаунт',
      deleteConfirmText: 'Вы уверены, что хотите удалить свой аккаунт? Это <span class="text-red-400 font-semibold">необратимо</span>!',
      deleteConfirmInstruction: 'Для продолжения введите "<span class="text-white font-medium">I am sure</span>" в поле ниже.',
      deleteConfirmPlaceholder: "Введите 'I am sure' для подтверждения",
      cancel: 'Отмена',
      deleting: 'Удаление...',
      confirmDelete: 'Подтвердить удаление',
    },
  },
  nav: {
    home: 'Главная',
    gameMechanics: 'Игровая Механика',
    seasonMechanics: 'Сезонная Механика',
    tools: 'Инструменты',
    buildPlanner: 'Планировщик Билдов',
    voidchartPlanner: 'Планировщик VoidChart',
    about: 'О Нас',
    impressum: 'Правовая Информация',
  },
  mobileNav: {
    menu: 'Меню',
    closeMenu: 'Закрыть меню',
    language: 'Язык',
  },
  footer: {
    copyright: '© {year} TLI Compendium. Все права защищены.',
  },
  home: {
    latest: 'ПОСЛЕДНЕЕ',
    filterAll: 'Все',
    filterGuides: 'Гайды',
    filterTools: 'Инструменты',
    filterUpdates: 'Обновления',
  },
  menuCategories: {
    combatMechanics: 'БОЕВАЯ МЕХАНИКА',
    gameSystems: 'ИГРОВЫЕ СИСТЕМЫ',
    seasons1to4: 'СЕЗОНЫ 1-4',
    seasons5to8: 'СЕЗОНЫ 5-8',
    seasons9to11: 'СЕЗОНЫ 9-11',
    seasons13: 'СЕЗОН 13',
  },
  menuItems: {
    // Combat Mechanics
    defences: 'Защита',
    defencesDesc: 'Броня, сопротивление и поглощение',
    ailments: 'Недуги',
    ailmentsDesc: 'Статусные эффекты и урон со временем',
    melee: 'Ближний бой',
    meleeDesc: 'Steep Strike, Multistrike и Combo',
    spells: 'Заклинания',
    spellsDesc: 'Spellburst, Tangle и Combo',
    minions: 'Прислужники',
    minionsDesc: 'Прислужники и как они работают',
    damageOverTime: 'Урон со временем',
    damageOverTimeDesc: 'Все об уроне со временем',
    buffsAndDebuffs: 'Баффы и дебаффы',
    buffsAndDebuffsDesc: 'Благословения, ослабление и другое',
    auras: 'Ауры',
    aurasDesc: 'Все об аурах и запечатанной мане',
    curses: 'Проклятия',
    cursesDesc: 'Все о проклятиях',
    // Game Systems
    crafting: 'Крафт',
    craftingDesc: 'Системы и механики крафта',
    // Seasons
    darkSurge: 'Темный Выброс',
    darkSurgeDesc: 'Механика сезона Темный Выброс',
    blacksail: 'Черный Парус',
    blacksailDesc: 'Механика сезона Черный Парус',
    cube: 'Куб',
    cubeDesc: 'Механика сезона Куб',
    aterna: 'Атерна',
    aternaDesc: 'Механика сезона Атерна',
    nightmare: 'Кошмар',
    nightmareDesc: 'Механика сезона Кошмар',
    whisperingMist: 'Шепчущий Туман',
    whisperingMistDesc: 'Механика сезона Шепчущий Туман',
    clockworkBallet: 'Заводной Балет',
    clockworkBalletDesc: 'Механика сезона Заводной Балет',
    theFrozenCanvas: 'Замерзший Холст',
    theFrozenCanvasDesc: 'Механика сезона Замерзший Холст',
    arcana: 'Аркана',
    arcanaDesc: 'Механика сезона Аркана',
    sandlord: 'Песчаный Лорд',
    sandlordDesc: 'Механика сезона Песчаный Лорд',
    outlaw: 'Вне закона',
    outlawDesc: 'Механика сезона Вне закона',
    overrealm: 'Сверхмир',
    overrealmDesc: 'Механика сезона Сверхмир',
    vorax: 'Воракс',
    voraxDesc: 'Механика сезона Воракс',
  },
  support: {
    message: 'Поддержите нас ❤️.',
  },
  auth: {
    login: 'Вход',
    logout: 'Выход',
    register: 'Регистрация',
    username: 'Имя пользователя',
    email: 'Электронная почта',
    displayName: 'Отображаемое имя',
    password: 'Пароль',
    confirmPassword: 'Подтвердите пароль',
    loginButton: 'Войти',
    registerButton: 'Зарегистрироваться',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    dontHaveAccount: 'Нет аккаунта?',
    loginSuccess: 'Вход выполнен успешно!',
    registerSuccess: 'Регистрация успешна! Вы автоматически вошли в систему.',
    logoutSuccess: 'Выход выполнен успешно',
    loginError: 'Ошибка входа',
    registerError: 'Ошибка регистрации',
    validation: {
      usernameRequired: 'Введите имя пользователя',
      usernameMinLength: 'Имя пользователя должно быть не менее 3 символов',
      usernameMaxLength: 'Имя пользователя должно быть не более 50 символов',
      emailRequired: 'Введите электронную почту',
      emailInvalid: 'Введите действительный адрес электронной почты',
      passwordRequired: 'Введите пароль',
      passwordMinLength: 'Пароль должен быть не менее 6 символов',
      passwordMaxLength: 'Пароль должен быть не более 100 символов',
      passwordsDoNotMatch: 'Пароли не совпадают',
      displayNameMaxLength: 'Отображаемое имя должно быть не более 100 символов',
      passwordRequirements: {
        title: 'Пароль должен содержать:',
        minLength: 'Не менее 6 символов',
        uppercase: 'Заглавную букву (A-Z)',
        lowercase: 'Строчную букву (a-z)',
        digit: 'Цифру (0-9)',
        special: 'Специальный символ (!@#$%^&* и т.д.)',
      },
    },
  },
}
