import type { UITranslations } from '../types'

export const uiTw: UITranslations = {
  settings: {
    title: '設定',
    account: {
      tab: '帳戶',
      title: '帳戶設定',
      displayName: '顯示名稱',
      displayNameDescription: '這是在整個網站上顯示的名稱。留空以使用您的用戶名。',
      displayNamePlaceholder: '輸入顯示名稱',
      displayNameSuccess: '顯示名稱更新成功！',
      saving: '儲存中...',
      saveDisplayName: '儲存顯示名稱',
      dangerZone: '危險區域',
      deleteAccountWarning: '一旦刪除您的帳戶，將無法恢復。此操作無法撤銷。您所有儲存的構建和數據將被永久刪除。',
      deleteAccount: '刪除帳戶',
      deleteConfirmText: '您確定要刪除您的帳戶嗎？這是<span class="text-red-400 font-semibold">不可逆轉的</span>！',
      deleteConfirmInstruction: '請在下方文本框中輸入「<span class="text-white font-medium">我確定</span>」以繼續。',
      deleteConfirmPlaceholder: "輸入'我確定'以確認",
      cancel: '取消',
      deleting: '刪除中...',
      confirmDelete: '確認刪除',
    },
  },
  nav: {
    home: '首頁',
    gameMechanics: '遊戲機制',
    seasonMechanics: '賽季機制',
    tools: '工具',
    buildPlanner: 'Build模擬器',
    voidchartPlanner: '虛空星圖規劃器',
    about: '關於',
    impressum: '法律聲明',
  },
  mobileNav: {
    menu: '選單',
    closeMenu: '關閉選單',
    language: '語言',
  },
  footer: {
    copyright: '© {year} TLI 寶典。保留所有權利。',
  },
  home: {
    latest: '最新',
    filterAll: '全部',
    filterGuides: '攻略',
    filterTools: '工具',
    filterUpdates: '更新',
  },
  menuCategories: {
    combatMechanics: '戰鬥機制',
    gameSystems: '遊戲系統',
    seasons1to4: '賽季 1-4',
    seasons5to8: '賽季 5-8',
    seasons9to11: '賽季 9-11',
    seasons13: '賽季 13',
  },
  menuItems: {
    // Combat Mechanics
    defences: '防禦',
    defencesDesc: '護甲、抗性和傷害減免',
    ailments: '異常狀態',
    ailmentsDesc: '狀態效果和持續傷害',
    melee: '近戰',
    meleeDesc: 'Steep Strike、Multistrike 和 Combo',
    spells: '法術',
    spellsDesc: '法術爆發、纏繞和連擊',
    minions: '召喚物',
    minionsDesc: '召喚物及其運作方式',
    damageOverTime: '持續傷害',
    damageOverTimeDesc: '關於持續傷害的一切',
    buffsAndDebuffs: '增益與減益',
    buffsAndDebuffsDesc: '祝福、弱化等',
    auras: '光環',
    aurasDesc: '關於光環和封印法力的一切',
    curses: '詛咒',
    cursesDesc: '關於詛咒的一切',
    // Game Systems
    crafting: '打造',
    craftingDesc: '打造系統和機制',
    // Seasons
    darkSurge: '黑暗湧動',
    darkSurgeDesc: '黑暗湧動賽季機制',
    blacksail: '黑帆',
    blacksailDesc: '黑帆賽季機制',
    cube: '魔方',
    cubeDesc: '魔方賽季機制',
    aterna: 'Aterna',
    aternaDesc: 'Aterna 賽季機制',
    nightmare: '噩夢',
    nightmareDesc: '噩夢賽季機制',
    whisperingMist: '低語之霧',
    whisperingMistDesc: '低語之霧賽季機制',
    clockworkBallet: '發條芭蕾',
    clockworkBalletDesc: '發條芭蕾賽季機制',
    theFrozenCanvas: '冰封畫布',
    theFrozenCanvasDesc: '冰封畫布賽季機制',
    arcana: '奧秘',
    arcanaDesc: '奧秘賽季機制',
    sandlord: '沙領主',
    sandlordDesc: '沙領主賽季機制',
    outlaw: 'Outlaw',
    outlawDesc: 'Outlaw 賽季機制',
    overrealm: 'Overrealm',
    overrealmDesc: 'Overrealm 賽季機制',
    vorax: 'Vorax',
    voraxDesc: 'Vorax 賽季機制',
  },
  support: {
    message: '支持我們 ❤️.',
  },
  auth: {
    login: '登入',
    logout: '登出',
    register: '註冊',
    username: '使用者名稱',
    email: '電子郵件',
    displayName: '顯示名稱',
    password: '密碼',
    confirmPassword: '確認密碼',
    loginButton: '登入',
    registerButton: '註冊',
    alreadyHaveAccount: '已有帳戶？',
    dontHaveAccount: '沒有帳戶？',
    loginSuccess: '登入成功！',
    registerSuccess: '註冊成功！您已自動登入。',
    logoutSuccess: '登出成功',
    loginError: '登入失敗',
    registerError: '註冊失敗',
    validation: {
      usernameRequired: '請輸入使用者名稱',
      usernameMinLength: '使用者名稱至少需要3個字元',
      usernameMaxLength: '使用者名稱不能超過50個字元',
      emailRequired: '請輸入電子郵件',
      emailInvalid: '請輸入有效的電子郵件地址',
      passwordRequired: '請輸入密碼',
      passwordMinLength: '密碼至少需要6個字元',
      passwordMaxLength: '密碼不能超過100個字元',
      passwordsDoNotMatch: '兩次輸入的密碼不一致',
      displayNameMaxLength: '顯示名稱不能超過100個字元',
      passwordRequirements: {
        title: '密碼必須包含:',
        minLength: '至少6個字元',
        uppercase: '大寫字母 (A-Z)',
        lowercase: '小寫字母 (a-z)',
        digit: '數字 (0-9)',
        special: '特殊字符 (!@#$%^&* 等)',
      },
    },
  },
}
